### ISSUE TITLE
Option to show Interim fields on results reports

### ISSUE THREAD

**Issue by Lunga001** [senaite/senaite.core#1001]
## Steps to reproduce
Add Report field(boolean) to Interim Fields 
## Current behavior
User does not have Report option on  Interim Fields 
## Expected behavior
User should be able to tick/untick the Report option
![capture-for-jira-screenshot-20180805-170328-463](https://user-images.githubusercontent.com/10023210/44311626-146b0480-a3eb-11e8-9359-3fa4fde16ebc.png)
![capture-for-jira-screenshot-20180805-170200-219](https://user-images.githubusercontent.com/10023210/44311627-146b0480-a3eb-11e8-952f-4ba5c0e7779d.png)

**Comment by Lunga001** [comment]
Also depends on https://github.com/senaite/senaite.core/issues/951

**Comment by xispa** [comment]
Hi @Lunga001 . There is the "hidden" option already, that is precisely to label the interims you don't want to be displayed neither in manage results view nor in results report. Is there any special reason why this "hidden" field does not fit well with your use case?

**Comment by xispa** [comment]
Aaa, I see now. By default, interims are never displayed in results report, even if they have the "hidden" field unchecked.

**Comment by grulisco** [comment]
Hi, I think it would be smart to distinguish between "hidden" and "report" options.
There are several interim values that must be entered, so these must not be hidden.
But only a subset of them shall appear in the report.
Actually hidden intertims (default values, constants) might be reported in some cases.

**Comment by xispa** [comment]
Fixed here: https://github.com/senaite/senaite.core/pull/1004
