### ISSUE TITLE
Worksheets: configuring display columns not possible

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1016]
## Steps to reproduce
Go to worksheet list view
Select filter "to be verified" or "verified"
Right-click column title to set visibility of columns

## Current behavior
Nothing happens,
Popup "Display columns" does not appear.

This happens, when there aren't **open** worksheets in the list.
With at least one **open** it works OK.

## Expected behavior
Popup "Display columns" appears as expected (see Screenshot) in all situations.

## Screenshot (optional)
![grafik](https://user-images.githubusercontent.com/25460329/45055657-bd268e80-b090-11e8-8995-440279ff991a.png)

**Comment by ramonski** [comment]
Seems like the `#list_toggle_cols` element can not be found by the `make_context_menu` method:

<img width="725" alt="" src="https://user-images.githubusercontent.com/713193/46558873-d1a7b200-c8ee-11e8-87c2-75d6b756a41a.png">


<img width="774" alt="" src="https://user-images.githubusercontent.com/713193/46558947-0e73a900-c8ef-11e8-8b5e-648fdd155d8d.png">

**Comment by ramonski** [comment]
Resolved in Version 1.3
