### ISSUE TITLE
 Object log of analyses: Missing popup title

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1061]
## Steps to reproduce
Create ARs and import their ASs into a worksheet.
Click on one analysis service in the worksheet.

## Current behavior
Popup appears with the object log of the service.
There is no information visible about the currently selected service.

## Expected behavior
Analysis service appears in the popup title bar. (IIRC)

## Screenshot (optional)
![grafik](https://user-images.githubusercontent.com/25460329/46754129-fc648280-ccc1-11e8-8443-7c7064fab9af.png)

**Comment by grulisco** [comment]
I suppose it is a display problem of the (IIRC black) font in the title bar of the popup.
See that the "X" in the close button in the upper right corner is missing too.

**Comment by ramonski** [comment]
Fixed as well in https://github.com/senaite/senaite.core/pull/1161
