### ISSUE TITLE
When creating a secondary AR the "Date sampled" can be modified

### ISSUE THREAD

**Issue by leonardorojass** [senaite/senaite.core#1066]
## Steps to reproduce
Create a secondary AR. The system permits to change the original sampling date for the secondary AR.

## Current behavior
The user can change the Sampling Date during the creation of a secondary AR.

## Expected behavior
The system should take the Sampling Date from the original AR, and should not permit the user to change it during the creation of a secondary AR.

**Comment by xispa** [comment]
Hi @leonardorojass , are you referring to "Date Sampled" or "Sampling Date"?
A related discussion about "Date Sampled" + secondary ARs topic here: https://github.com/senaite/senaite.core/issues/863
Also, related PRs:
- [Sample's Date Received editable only when `received` analyses exist](https://github.com/senaite/senaite.core/pull/899)
- [Secondary AR changes received date of sample](https://github.com/senaite/senaite.core/pull/1049)

**Comment by leonardorojass** [comment]
Hi @xispa , thanks for the "Date Sampled" related discussion. For that topic ("Received date") the issue is already fixed and works fine.

The current issue is with the "Date Sampled". When the secondary AR is created the user can change the "Date Sampled" date. Additionally, when the default value (original date) is not modified it is not saved during the secondary AR creation. A new value must be selected to get it saved. At the Sample level the original date is not changed but at the AR level it does not happen. This generates confusion for the user as well as for the PDF report the date is not shown correctly.

![1b](https://user-images.githubusercontent.com/2072052/47966194-12aaf780-e050-11e8-94a8-6e60f64a530c.png)
![2a](https://user-images.githubusercontent.com/2072052/47966190-0c1c8000-e050-11e8-9b53-e4ec8b49f208.png)
![1a](https://user-images.githubusercontent.com/2072052/47966195-12aaf780-e050-11e8-99d1-44606745cd6a.png)

**Comment by xispa** [comment]
This has been fixed in 1.3 thanks to https://github.com/senaite/senaite.core/pull/1284
