### ISSUE TITLE
Worksheets - "to close" Button and no empty WS creation

### ISSUE THREAD

**Issue by leonardorojass** [senaite/senaite.core#1067]
There should be a way to closed "open worksheets" that does not have any analysis or if for any given reason it should be closed. Currently it is not possible to have an alternative way to close Worksheets. Sometimes empty Worksheets are created when using a template (if no associate analysis are available). This function should be enable only for Lab Managers.

Additionally, it will be nice if the system recognises that there will be no analysis for the selected worksheet template, and then it is not created but a message is shown to the user.

**Comment by xispa** [comment]
https://github.com/senaite/senaite.core/pull/1291 allows the removal of empty worksheets
