### ISSUE TITLE
Reflex rule folder: Add-Button leads to Add client page

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1069]
## Steps to reproduce
Go to setup/reflexrule folder
Click on "Add"

## Current behavior
Misleads to empty "Add Client"-Page, which is nonsense in this context.

## Expected behavior
"Add"-widget is obsolete, see "Add reflex rule" next to it, which works correct.
It should be removed.

## Screenshot (optional)
![grafik](https://user-images.githubusercontent.com/25460329/47733497-a05da000-dc68-11e8-9418-26300d6d74ac.png)

**Comment by xispa** [comment]
@grulisco , please install `senaite.reflex` add-on:
https://github.com/senaite/senaite.reflex

The reflex rule machinery that came by default with `senaite.core` has been ported to `senaite.reflex`, with improved behavior and functionalities. Hence, the code for reflex testing that still comes by default with `senaite.core`will be removed very soon in next release (1.3.0) in favor of `senaite.reflex`.
