### ISSUE TITLE
Min / Max symbol inverted in Sample Specifications  - Function works fine

### ISSUE THREAD

**Issue by leonardorojass** [senaite/senaite.core#1075]
The sample specifications functionality works fine but the Min/Max symbol in the Specification Form is shown inverted.

![screen shot 2018-11-04 at 17 18 39](https://user-images.githubusercontent.com/2072052/47966741-3c671d00-e056-11e8-8cc7-ba88ba15f85b.png)

**Comment by ramonski** [comment]
Hi @leonardorojass,

according to Wikipedia, the "greater than" sign is `>` (https://en.wikipedia.org/wiki/Greater-than_sign) and the "less than" sign is `<` (https://en.wikipedia.org/wiki/Less-than_sign)

Therefore, the *Min operator* states that everything *greater or equal* to that value is in range, and the *Max operator* states that everything *lower or equal* to that value is in range.

For Example, having this specification:

<img width="1186" alt="ramon senaite 2018-12-24 23-05-44" src="https://user-images.githubusercontent.com/713193/50407099-fd8d5200-07d0-11e9-8244-8099853b3740.png">

Results in these valid results:

<img width="1183" alt="h2o-0007-r01 senaite 2018-12-24 23-10-36" src="https://user-images.githubusercontent.com/713193/50407113-3c230c80-07d1-11e9-8a5e-8a938f85adc4.png">

And in these invalid results:

<img width="1188" alt="h2o-0007-r01 senaite 2018-12-24 23-12-22" src="https://user-images.githubusercontent.com/713193/50407123-62e14300-07d1-11e9-9415-8a3a4b06f2c7.png">

**Comment by leonardorojass** [comment]
Hi @ramonski,

Thank you for the examples. Seems to be my confusion at the moment to read only the setup columns. Everything is clear now.
