### ISSUE TITLE
Not all active clients are shown in clients drop menu for Productivity Reports

### ISSUE THREAD

**Issue by leonardorojass** [senaite/senaite.core#1084]
## Steps to reproduce
Go to productivity reports and then open the clients drop menu. 

## Current behavior
Not all active clients are shown in the drop menu list.

## Expected behavior
All active (and Dormant?) clients should be shown in this list when no other filter applies.

## Screenshot (optional)
<img width="428" alt="screen shot 2018-11-11 at 9 53 39 pm" src="https://user-images.githubusercontent.com/2072052/48318144-495ab200-e5fc-11e8-815d-1e47dde630d2.png">

**Comment by xispa** [comment]
Fixed in https://github.com/senaite/senaite.core/pull/1237
