### ISSUE TITLE
Batch View: status widget missing

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1086]
## Steps to reproduce
Create batch
Go to batch view

## Current behavior
The common status widget for workflow transitions in the top right corner is missing.

## Expected behavior
Status widget is displayed.

## Screenshot (optional)
![grafik](https://user-images.githubusercontent.com/25460329/48359120-97bf8d80-e69c-11e8-9a97-ef2ed1694e55.png)

**Comment by ramonski** [comment]
Batches can be still transitioned via the listing view:

<img width="1147" alt="Batches — SENAITE 2019-05-08 11-13-11" src="https://user-images.githubusercontent.com/713193/57363903-54913380-7182-11e9-8298-0bd126c8ed7b.png">

**Comment by grulisco** [comment]
Better handled by #1235
