### ISSUE TITLE
Linking LabContacts to LDAP-user not possible 

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1109]
## Steps to reproduce
- Create senaite users
- Create and edit LabContact
- Go to Login details

## Current behavior
Warning message appears, see screenshot
No users are listed

## Expected behavior
Available users are listed for selection
User can sussessfully linked

## Screenshot (optional)
see senaite.ridingbytes.com
![grafik](https://user-images.githubusercontent.com/25460329/49186630-767dc300-f365-11e8-8db4-fcb3d111c563.png)

**Comment by grulisco** [comment]
Might be a LDAP problem at our testsite. After deactivating LDAP authentification linking users works properly.

**Comment by ramonski** [comment]
We use the Plone API for searching the users and there is this related issue in the `plone.api` for it:
https://github.com/plone/plone.api/issues/359

**Comment by grulisco** [comment]
Yes indeed, it's a problem with LDAP integration only. Changing title now...
