### ISSUE TITLE
Issues with new transposed worksheet view

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1126]
## Steps to reproduce
Create ARs and corresponding worksheet
View transposed worksheet

## Current behavior
- ARs sorted by sortkey descendng
- Interims not labelled
- hidden Interims visible
- attachments not listed
- no global toggle for services
- no object log of analysis
- result options not working

## Expected behavior
- ARs sorted by sortkey ascending
- Interims labelled
- hidden Interims stay hidden
- attachments listed 
- global toggle for services, e.g. per AR
- object log of analysis by click onto AS
- working result options

**Comment by ramonski** [comment]
@grulisco regarding point 3: "hidden Interims visible"
Can you please check if the hidden checkbox is selected on the service and *not* on the calculation?
As soon as a calculation is linked to an Analysis Service, the interim fields get copied and thus, the Analysis Service has precedence over the Calculation for the Interims in Analyses inside an Analysis Request

**Comment by grulisco** [comment]
@ramonski point 3: Yes, hidden interims in my case are selected on analysis service and not on calculation. In classic view they are hidden anyway...
