### ISSUE TITLE
Statement error

### ISSUE THREAD

**Issue by ushcadh** [senaite/senaite.core#1172]
## Steps to reproduce
Created and invoice batch for already published results
https://qa.quantum.bikalims.org/invoices/invoicebatch.2018-12-18.7552176647
## Current behavior
Did not create any statements only gives this few lines

![capture 2018-12-18 at 12 11 29](https://user-images.githubusercontent.com/45965037/50148589-926be900-02c1-11e9-94c0-4cadadaef9ff.png)

If you look at the Sample self it still shows Proforma invoice even after the statement is generated, so it did not generate an invoice.
https://qa.quantum.bikalims.org/clients/client-2/Che18-00457-R1/invoice

Can you maybe have a look at this please.  Thnks Ushca de Haast - Quantumlab

**Comment by xispa** [comment]
Thanks for reporting @ushcadh . This statements/invoicing functionality is kind of old-school code and don't think is reliable at the moment. What version of Senaite are you using?

**Comment by ushcadh** [comment]
As far as I know, Bika upgraded us to the newest version. S1.2.9

From https://quantum.bikalabs.com/portal_setup/manage_upgrades

The profile "bika.lims:default" is currently upgraded to version 1.2.9.
The filesystem version for the "bika.lims:default" profile is currently 1.2.9.

**Comment by ramonski** [comment]
Invoice Batches were removed as of https://github.com/senaite/senaite.core/pull/1296.
However, Invoices can still be generated per Sample.
