### ISSUE TITLE
Detection Limit handling in the Frontend/Backend

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.core#1184]
## Description

This issue is a high level description of the frontend/backend behavior of the detection limit functionality

<img width="1197" alt="calcium-_-senaite-2018-12-25-21-20-36" src="https://user-images.githubusercontent.com/713193/50470687-de014f80-09b1-11e9-94d4-8061c20622f9.png">

## Frontend

- If "Detection Limit Selector" is disabled: selection list is not rendered. User can only input a numeric value, that is the exact result of the test.
 - If "Detection Limit Selector" is enabled: a selection list is rendered with options ">", "<", ""
- Option "<" is selected: the input field is set to readonly and is auto-filled with the LDL value: `analysis.getLowerDetectionLimit()`
- Option ">" is selected: input field is set to readonly mode and is auto-filled with the UDL value:
`analysis.getUpperDetectionLimit()`
- Option "" (empty) is selected: input field is set to edit mode and emptied. User can input a numeric value, that is the exact result of the test.
- If together with "Detection Limit Selector", "Allow manual input of detection" is enabled. Applies exactly the same criteria as above, but input field is always in edit mode, regardless of the option selected.

## Backend

- Option="<" and Input value="0.05" (note the input value is numeric and defaults to service's LDL)
```
analysis.setResult("<0.05")
```
- Option=">" and Input value="1000"
```
analysis.setResult(">1000")
```
- Option="" (empty) and Input value=23 (this is a discrete result)
```
analysis.setResult(23)
```

**Comment by leonardorojass** [comment]
Is this issue related or the cause why when an AS has "Display a Detection Limit selector" active, all the results are saved like ">" or "<", and it is not possible to save the result without choosing ">""<"?

**Comment by xispa** [comment]
@leonardorojass , you shouldn't have this problem with latest version of `master`

**Comment by grulisco** [comment]
@xispa:
  * If together with "Detection Limit Selector", "Allow manual input of detection" is enabled. Applies exactly the same criteria as above, but input field is always in edit mode, regardless of the option selected.

This option does not work here. After submitting result the "<" is lost in the result string.
Reopen issue?
