### ISSUE TITLE
Saving interims after autofill

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1202]
## Steps to reproduce
- Create, receive samples with analyses containing autofill interim fields and some more
- Create worksheet, assign those analyses
- Autofill values of interims

## Current behavior
In my example (see screenshots) after autofilling the interims the values shall be saved and results shall be calculated, but it is very cumbersome:
- the service is not automatically toggled for saving
- manual toggling the service does not provide the save button
- toggle and save button only appears after editing one interim

One has to overwrite at least one autofilled value per service, so the advantage of autofill is lost in most cases.

## Expected behavior
Autofill interims should act like manual entries, that take care of automatic toggle and save button.

## Screenshot (optional)
![grafik](https://user-images.githubusercontent.com/25460329/51143910-01504980-1850-11e9-9140-755282f75133.png)

![grafik](https://user-images.githubusercontent.com/25460329/51144340-0f529a00-1851-11e9-8a8f-2a19c1d879b7.png)

**Comment by xispa** [comment]
Thanks @grulisco, we missed to consider the "autofill" option in new manage results view
