### ISSUE TITLE
Error while importing setup data

### ISSUE THREAD

**Issue by Migulo** [senaite/senaite.core#1211]
## Steps to reproduce

Import setup data via "Load from file"

![image](https://user-images.githubusercontent.com/38714119/51666393-046cd780-1fbe-11e9-897c-19dc9458a9ff.png)

Test.xlxs was used without any change

Senaite.core version: 1.29

## Current behavior

Error occurs:

![image](https://user-images.githubusercontent.com/38714119/51666336-e1dabe80-1fbd-11e9-90af-6518c90194db.png)

## Expected behavior

Import should work without errors

**Comment by ramonski** [comment]
Hi @Migulo, you uploaded the XLSX file via the upload button? Did you open the file before in MS Excel? Because I noted that Excel tries to "repair" that file and then it is corrupted.

Please try to submit the test data via this option:

<img width="1594" alt="senaite 2019-01-24 10-01-57" src="https://user-images.githubusercontent.com/713193/51666993-49ddd480-1fbf-11e9-891d-c9abae0e15b0.png">

**Comment by Migulo** [comment]
OK, but where is "this" specific "test.xlxs" located?

**Comment by ramonski** [comment]
It is located in the codebase of `senaite.core` in `senaite.core/bika/lims/setupdata/test/test.xlsx`, but you can traverse it directly from GitHub with the link provided above:

<img width="1528" alt="senaite core 2019-01-24 12-15-28" src="https://user-images.githubusercontent.com/713193/51674725-c5e11800-1fd1-11e9-9285-0c304ca19bea.png">

**Comment by Migulo** [comment]
Sorry for my unspecific question:

There to get it online is clear, but where do I have to put it in my local installation? As I can not choose any path/file at "Select existing file" I wonder which "existing file" is used and where to find or put it.

**Comment by ramonski** [comment]
If you installed the `senaite.core` package from [PyPI](https://pypi.org/project/senaite.core), then it is located in the source package, e.g.: https://files.pythonhosted.org/packages/70/ff/e43a79c5eca624950d9888283d305b929f3d8dda193b3dd8bfafb5f72110/senaite.core-1.2.9.1.zip

This package get downloaded to your "buildout-cache" in the downloads folder:

<img width="682" alt="senaite zsh 2019-01-24 13-09-10" src="https://user-images.githubusercontent.com/713193/51677249-45261a00-1fd9-11e9-8fe4-8370f79ef125.png">

From that source package, an "Egg" is created in your local installation:

<img width="677" alt="senaite zsh 2019-01-24 13-07-05" src="https://user-images.githubusercontent.com/713193/51677171-ff695180-1fd8-11e9-832d-338463d68d6d.png">

**Comment by ramonski** [comment]
Closing this one, please re-open if you encounter further problems regarding this issue @Migulo
