### ISSUE TITLE
Cannot save sample results in Batch Book

### ISSUE THREAD

**Issue by faytrow** [senaite/senaite.core#1250]
## Steps to reproduce
Navigate to **Batches** listing.
Select a Batch containing a sample without submitted results (Sample is in "Received" state).
Navigate to the **Batch Book** tab.
Enter test results for unsubmitted samples.
Press 'Submit'.
## Current behavior
The results are not saved, and the screen is navigated to a page that does not exist.
In release 1.3 the page does not navigate, but the results are still not saved. (Per @ramonski)
## Expected behavior
Results entered should be saved for the sample they are entered for.
Sample should be moved to "To Be Verified" state.
## Screenshot (optional)
![batch book bug](https://user-images.githubusercontent.com/16670300/53257247-ace28a00-3697-11e9-9c18-4df3930b7755.png)

**Comment by ramonski** [comment]
This was fixed in https://github.com/senaite/senaite.core/pull/1966
