### ISSUE TITLE
Poor performance with many calculations 

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1252]
## Steps to reproduce
- Create, receive several samples with calculated services (e.g. Total Hardness)
- Create new worksheet
- Import those analysis services into worksheet
- Enter and save some results and let calculate...

## Current behavior
In this large worksheet the time for showing calculated results after saving of manually entered results is much too long and not responsive.
In the demo example it's at least 30 seconds, while I worked only 2 results one one sample here,
On my test machine even longer, depending on the number of services.

## Expected behavior
Calculations are executed and displayed within a few seconds, as it was in versions <=1.2

## Screenshot (optional)
see demo senaite.ridingbytes.com
![grafik](https://user-images.githubusercontent.com/25460329/53499800-66cb6300-3aa9-11e9-906e-2a2ccc1bb3c7.png)

**Comment by ramonski** [comment]
Closed by https://github.com/senaite/senaite.core.listing/pull/9
