### ISSUE TITLE
Adding Analyses to an existing Worksheet in a non-open status fails

### ISSUE THREAD

**Issue by Espurna** [senaite/senaite.core#1281]
## Steps to reproduce

1- Open an already created Worksheet with assigned Analyses.
2- Open the label to add more analyses to the worksheet.
3- Select an analysis and assign it to the worksheet

## Current behavior

The new assigned analyses are **not** assigned to the worksheet and no error is displayed.

## Expected behavior

The new assigned analyses to be assigned to the worksheet

## Screenshot (optional)

First screen of the Worksheet:

![Selection_008](https://user-images.githubusercontent.com/7425587/54376209-da14cd80-4682-11e9-83bb-3fde98cf5ce9.png)

Analyses selected:

![Selection_009](https://user-images.githubusercontent.com/7425587/54376221-e13bdb80-4682-11e9-9203-efd30e1fca7b.png)

Worksheet/Analyses view after clicking on "assign":

![Selection_010](https://user-images.githubusercontent.com/7425587/54376223-e436cc00-4682-11e9-8b86-e80c40c26607.png)

**Comment by ramonski** [comment]
Seems like `addAnalysis` of Worksheets only allow to add Analyses if the state is open:
https://github.com/senaite/senaite.core/blob/master/bika/lims/content/worksheet.py#L162

**Comment by xispa** [comment]
`worksheet_workflow` has the transition `rollback_to_open` available in `to_be_verified` state:
https://github.com/senaite/senaite.core/blob/master/bika/lims/profiles/default/workflows/bika_worksheet_workflow/definition.xml#L110-L114

And we always try to do a rollback on analysis assignment here: https://github.com/senaite/senaite.core/blob/master/bika/lims/content/worksheet.py#L207

I think we can safely remove this check if we add a condition in analysis guard to not allow the assignment if the current worksheet is closed or verified.

**Comment by xispa** [comment]
Umm, I think is better to leave it like this, but do not display the Add Analyses view if the Worksheet is not in an open state.

**Comment by xispa** [comment]
Umm, somehow, not allowing to add analyses when the worksheet is in `to_be_verified` state is the expected behavior. Also, considered in the doctest:

```rst
But if I remove the remaining analysis, the status of the Worksheet is promoted
to `to_be_verified`, cause all the analyses assigned are in this state:

    >>> fe = filter(lambda an: an.getKeyword() == "Fe", analyses)[0]
    >>> worksheet.removeAnalysis(fe)
    >>> fe.getWorksheet() is None
    True
    >>> api.get_workflow_status_of(fe)
    'unassigned'
    >>> api.get_workflow_status_of(worksheet)
    'to_be_verified'

And now, I cannot add analyses anymore:

    >>> worksheet.addAnalysis(fe)
    >>> filter(lambda an: an.getKeyword() == "Fe", worksheet.getAnalyses())
    []
    >>> fe.getWorksheet() is None
    True
    >>> api.get_workflow_status_of(fe)
    'unassigned'

Neither remove:

    >>> worksheet.removeAnalysis(au)
    >>> map(lambda an: an.getKeyword(), worksheet.getAnalyses())
    ['Au']
    >>> au.getWorksheetUID() == api.get_uid(worksheet)
    True
    >>> api.get_workflow_status_of(au)
    'to_be_verified'
```
*excerpt from https://github.com/senaite/senaite.core/blob/master/bika/lims/tests/doctests/WorkflowAnalysisAssign.rst#assign-transition-and-guard-basic-constraints*

So, what do you suggest?
a) Boil out the check and allow the addition of analyses when worksheet is in `to_be_verified` status
b) Only display the "Add *" views from inside Worksheet when is in an `open` status
