### ISSUE TITLE
Traceback when using "Submit" of the global WF menu

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.core#1306]
## Steps to reproduce

This is a side-effect of an edge case. When a Sample has **all Analyses verified**, but contains also retracted and rejected Analyses, the status remains in "received".
The WF Menu of the top right corner shows then the submit action, which causes this traceback:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.workflow, line 122, in __call__
  Module bika.lims.browser.workflow.analysis, line 64, in __call__
AttributeError: setUncertainty
```

## Current behavior

- Sample is not automatically transitioned to the state "verified"
- WF menu shows "submit" transition
- Traceback occurs

## Expected behavior

The sample is automatically transitioned to the state "verified"

## Screenshot (optional)

Workflow Menu:

<img width="366" alt="" src="https://user-images.githubusercontent.com/713193/55142019-f82b0500-513b-11e9-8a17-11a9a7bc335c.png">

All contained Analyses:

<img width="696" alt="" src="https://user-images.githubusercontent.com/713193/55142250-75567a00-513c-11e9-8f45-8daae2d38dc4.png">

**Comment by xispa** [comment]
After several tries, I've been able to reproduce the exact use case when this happens:

- Create AR and receive it
- Submit a result for all analyses. The AR transitions to `to_be_verified`
- Retract a given analysis. The AR transitions to `received`
- **Reject the retest without result**. The AR does **not** transition to `to_be_verified` (remains in `received`)
- Verify all analyses. AR remains in `received` status

This is not about the "Submit" transition from Sample, cause the transition should take place automatically.

**Comment by ramonski** [comment]
Thanks for your support @xispa !
