### ISSUE TITLE
Only default result field is updated after 2-Dimensional-CSV import

### ISSUE THREAD

**Issue by jmcole003** [senaite/senaite.core#1313]
## Steps to reproduce
1. After creating a new instrument (Nanodrop One in this case), set the Import Data Interface to 2-Dimensional-CSV
2. In Analysis Services, add a service (“Nanodrop Quantification”) and set analysis keyword (“nanodrop”) as well as additional interim field keywords (“A260A280” and “A260A230”, see below)
3. Create a spreadsheet like the one below containing results data, including keywords for analysis across the top row.
4. Add an Analysis Request with the analysis service and then ‘Receive’ samples.
5. Import CSV spreadsheet from the “Import” option on the Home page, using the created instrument.

![screenshot_02](https://user-images.githubusercontent.com/40611585/55264972-43303f80-5244-11e9-9958-4b192876bd7c.jpg)

![screenshot_01](https://user-images.githubusercontent.com/40611585/55264858-d1f08c80-5243-11e9-823b-76e1dbd3138b.jpg)

Seems like a similar issue to https://github.com/senaite/senaite.core/issues/719

## Current behavior
Only default results field is updated. 

(Note, if top row in CSV spreadsheet is edited so that the analysis keyword (“nanodrop”) is last, then both A260/A280 and A60/230 fields update but default results are empty.) 

![screenshot_04](https://user-images.githubusercontent.com/40611585/55265027-74107480-5244-11e9-9488-4943610ebf14.jpg)

![screenshot_03](https://user-images.githubusercontent.com/40611585/55265032-770b6500-5244-11e9-92f3-62653f8636b6.jpg)

## Expected behavior
All relevant fields will be updated with imported results.

**Comment by ramonski** [comment]
Pretty sure that this is fixed in `2.x` or in this refactoring: https://github.com/senaite/senaite.core/pull/1855
