### ISSUE TITLE
Sample view ignores AS categories

### ISSUE THREAD

**Issue by andersonsmith** [senaite/senaite.core#1323]
## Steps to reproduce
View the manage results tab of a sample with multiple categories

## Current behavior
Analysis services are listed alphabetically without any categorization.

## Expected behavior
AS grouped in categories and respect sort ID's.

**Comment by xispa** [comment]
Analyses have always been categorized in "Add analyses" views, "Analysis Services" listings, "Sample Add", etc. but as far as I know, they've never been categorized in manage results views

**Comment by grulisco** [comment]
In our instance analyses are sorted (not grouped) correctly by category, by sortkey, alphabetically in sample view and **manage results** view.
The demo senaite.ridingbytes.com behaves like @andersonsmith described. The only difference I see, is that there are no sortkeys at all.

**Comment by ramonski** [comment]
As far as I remember they have been categorized before 1.3.0 and sorted by sort_key with a fallback to alphabetically. Therefore, I think it makes sense to re-add that in the listing

**Comment by xispa** [comment]
Got it, apologies for the confusion :+1:

**Comment by andersonsmith** [comment]
Yes, manage results was always categorized in previous versions.

**Comment by xispa** [comment]
More details here: https://github.com/senaite/senaite.core/issues/1400

**Comment by ramonski** [comment]
Implemented in https://github.com/senaite/senaite.core/pull/2140
