### ISSUE TITLE
localhost dosn't work on the browser

### ISSUE THREAD

**Issue by ahmadti** [senaite/senaite.core#1350]
I've install Plone-4.3.18-UnifiedInstaller and I add senait successfully but when I tray to open my localhostt:8080 firfox shows "Unable to connect

Firefox can’t establish a connection to the server at localhost:8000.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web"

I'm using Ubuntu 18.04.2 LTS 

PLz help

**Comment by ramonski** [comment]
Hi @ahmadti,

If you used the unified installer you'll probably have a ZEO cluster setup. Therefore, you need to start the ZEO (Database) server first with `bin/zeoserver start` and start then a worker instance with `bin/client1 start` or to start in foreground use `bin/client1 fg`.

It is also likely that the instance is running in this setup on `http://localhost:8081` and not on `http://localhost:8000` as you mentioned above.

Please also see https://docs.plone.org/4/en/manage/installing/installation.html for further information how to get Plone up and running.

However, this actually an installation based issue and does not describe a bug in `senaite.core`. Therefore I'll close this issue for now.
