### ISSUE TITLE
Worksheet does not show the contained analyses

### ISSUE THREAD

**Issue by Espurna** [senaite/senaite.core#1360]
## Steps to reproduce

All the process was done using the same user with LabMan role.

- Create a worksheet and assign analyses to it:

![Selection_029](https://user-images.githubusercontent.com/7425587/57464526-2fcdb680-727d-11e9-8b81-dea0c33df264.png)

Assigning analyses:

![Selection_030](https://user-images.githubusercontent.com/7425587/57464573-3ceaa580-727d-11e9-99de-948ddad07eb2.png)

## Current behavior

The worksheet displays 0 analyses:

![Selection_031](https://user-images.githubusercontent.com/7425587/57464612-4c69ee80-727d-11e9-8d6e-3a9b223ffa0c.png)

Analyses are "tagged" as they were assigned to a worksheet and removed from the list:

![Selection_033](https://user-images.githubusercontent.com/7425587/57464785-a2d72d00-727d-11e9-9efa-361aaf5dffa7.png)

If you go to the Sample, the analyses will have the worksheet icon as well.

## Expected behavior

The worksheet does display the assigned analyses

**Comment by ramonski** [comment]
Hi @Espurna, can you please list the versions you are using?
From interest would be the installed versions of `senaite.core`, `senaite.core.listing` and `senaite.lims`

**Comment by Espurna** [comment]
I am afraid that I do not have access to the server in order to obtain the git tag, I can tell the following:

SENAITE CORE LISTING 1.2.0
SENAITE Core 1.3.1
SENAITE IMPRESS 1.2.0
SENAITE LIMS 1.4.0
SENAITE STORAGE 1.0.0
Plone 4.3.15 (4317)

**Comment by ramonski** [comment]
I think that's the related PR which fixed this issue: https://github.com/senaite/senaite.core/pull/1289
Can you check if this one is in?

**Comment by Espurna** [comment]
I am not sure if this was the same case or if that pr is the source of this (new) problem. The issue I am reporting is that Analyses are assigned, but not displayed under the worksheet.
