### ISSUE TITLE
Add Chinese as another available language.

### ISSUE THREAD

**Issue by Espurna** [senaite/senaite.core#1374]
Chinese has as many translated strings as German or Spanish. Therefore, I suggest including it as another default language.

![Selection_037](https://user-images.githubusercontent.com/7425587/57959744-296db900-78d3-11e9-83e6-7f0d0f0fcaf6.png)

**Comment by ramonski** [comment]
Added for senaite.core 1.3.3, as well as Thai and Polish:

![SENAITE2 2020-02-13 08-56-48](https://user-images.githubusercontent.com/713193/74412971-cf3c5d00-4e3e-11ea-98ac-91a958f4a61e.png)
