### ISSUE TITLE
Client object list empty when logged in as user linked to Client contact

### ISSUE THREAD

**Issue by bioinfo2019** [senaite/senaite.core#1380]
## Steps to reproduce

1) Install latest senaite LIMS version 1.3 

2) Import the supplied setup data to get a test lab working.

3) Log in as a client contact (e.g. ritamo)

## Current behavior

Clicking on the Client link in the navigation portal shows an empty Client object list 

## Expected behavior

Clicking the link should show the client(s) to which the linked user has access to.

## Screenshot (optional)

![image](https://user-images.githubusercontent.com/5627112/58079273-cf266e00-7bda-11e9-9ab0-408f42e4313d.png)

**Comment by ramonski** [comment]
Thanks for reporting @bioinfo2019 

Does this also happen when you link a new user to a client contact or only with the users from the demo data?

**Comment by bioinfo2019** [comment]
It also happens with a new user, created after the import of the setup data

**Comment by bioinfo2019** [comment]
I found that if in ZMI I update the portal_catalog, then the client(s) show up in the list. Investigating further I found that going into portal_catalog->Indexes and reindexing "allowedRolesAndUsers" solves the problem. I haven't tried to figure out where in the senaite code that could/should happen, but perhaps this helps track the problem down
