### ISSUE TITLE
Error: Labclerks viewing verified worksheets

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1396]
## Description

Labclerks cannot view worksheets in verified status.

## Reproduction guide

- Login with labclerk privileges
- Goto Worksheet view
- select one of the verified worksheets

## Observed behaviour
Browser Error: ERR_TOO_MANY_REDIRECTS

## Expected behaviour

View verified worksheet

## Versions

- OS: Linux

- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

**Comment by grulisco** [comment]
@xispa @ramonski: On our updated testmachine labclerks can access verified worksheets now, but they are empty. samples and analyses are not displayed yet. Please reopen issue.

**Comment by grulisco** [comment]
still a problem after upgrade to core 1.3.3

**Comment by ramonski** [comment]
The problem was found in the add-on and not in `senaite.core`. Closing.

**Comment by ramonski** [comment]
@grulisco please test on your system and confirm that the problem is resolved.
The problem was the same as resolved here: https://github.com/senaite/senaite.core/pull/1479 but in the domain of the add-on.

**Comment by grulisco** [comment]
@confirmed for test instance.

**Comment by grulisco** [comment]
@ramonski confirmed for productive instance :smile:
