### ISSUE TITLE
Using {Client} in ID-Server for AR generates Error

### ISSUE THREAD

**Issue by RaabJoh** [senaite/senaite.core#1411]
## Description

Using {Client} in ID-Server generates Error

## Reproduction guide

Using the term {client} in ID server name generation for AR samples generates an error during AR generation. "Error Client" is displayed and random number/letter AR is generated instead of adding the client ID to the SampleName as described in the manual. {ClientId} works fine for AR.

## Versions

- OS: Ubuntu 16.04
- senaite.core: `1.3.1`

**Comment by xispa** [comment]
Hi @RaabJoh , the supported keyword in ID server for Sample creation is `clientId`. Just replace `{client}` by `{clientId}` for `analysisrequest` type in Setup > ID Formatting
