### ISSUE TITLE
I cannot load contacts in batch samples

### ISSUE THREAD

**Issue by nascimf** [senaite/senaite.core#1432]
## Description
When I create a new batch, when trying to add the samples, the contact field does not display a list of them

## Versions

- OS: Linux

- senaite.core: `master` 1.3.1
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`
![problema lotes](https://user-images.githubusercontent.com/54465150/64120454-9f0e6f80-cd72-11e9-855c-f27278428d76.png)

**Comment by xispa** [comment]
@nascimf is this still an issue with latest master? Cannot reproduce. Also, please note that we've done several improvements regarding Batches lately: https://github.com/senaite/senaite.core/pull/1450
