### ISSUE TITLE
Hidden settings of analysis services not populated on Sample creation with Template

### ISSUE THREAD

**Issue by amediphoko** [senaite/senaite.core#1437]
## Description

When adding an analysis request using a template, the hidden settings are not populated to the analyses when the sample is created

## Reproduction guide

1. Add AR Template
2. Select the required analyses and mark as hidden
3. Save the AR Template
1. Add new analysis request and save

## Observed behaviour

The analyses is created without populating the hidden settings from the ar template.

## Expected behaviour

The hidden settings from the template should be populated to the analyses created.

## Versions

- senaite.core: `master`

**Comment by grulisco** [comment]
Supposedly the same problem as in senaite/senaite.core#1326
