### ISSUE TITLE
Secondary samples - removal of analysis profile not possible

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1471]
## Description
After last update to master last weekend, the AR add form is not working properly with secondary samples. Secondary samples are often needed to alter or to extend the original profile while keeping the original sample id.

## Reproduction guide
- create a sample with some profiles
- recognize the profile is wrong and changing afterwards is not possible
- create a secondary sample (in order to assign a new profile)

## Observed behaviour
Somehow confusing behaviour:
- After entering the primary sample all profiles of the primary samples are set
- but the corresponding services are not ticked
- profiles cannot be removed
- sometimes trial causes the services to be unticked
- but all other services are ticked again
- so changing the profile isn't possible at all

-> Bug

## Expected behaviour
The former one:
- keep the profile empty, when creating a secondary sample

## Versions

- OS: Linux

- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

**Comment by xispa** [comment]
Hi @grulisco , same behavior with Template. The system expects that you want to fill all field values with same information as the primary you selected. You can edit any field value copied from the Primary if you clear the Primary Sample field thereafter.

**Comment by grulisco** [comment]
Hi @xispa : I'm afraid, this workaround does not work here.
After clearing primary entry and removing an profile, primary profiles appear again after a few seconds.
I wonder if this would lead to a secondary sample or to a normal copy.
Nothing against sensible suggestions in the sample add form, but forcing secondary samples being an exact copy does not make sense at all IMHO, particularly for profiles.
I hope this behaviour is not intended...
