### ISSUE TITLE
import samples data - csv 

### ISSUE THREAD

**Issue by rmmc81** [senaite/senaite.core#1623]
## Description

Trying to import samples results to senaite with csv 

## Reproduction guide

Can't find a spreedsheet model to import this data, all other modules work 

## Observed behaviour

<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

## Expected behaviour

<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

## Versions

- OS: Linux

- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

## Traceback
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by ramonski** [comment]
Sorry, I do not understand this ticket. Is this a bug or a question?
If this is a bug, please add a new ticket with a proper title, description, reproduction guide, observed and expected behavior.
If this is a question, please post to our community site: https://community.senaite.org
