### ISSUE TITLE
Senaite barcode - EAN-13 

### ISSUE THREAD

**Issue by rmmc81** [senaite/senaite.core#1624]
## Description

Need to use EAN-13 barcodes in Senaite 
It is possible? 

## Reproduction guide

<<REPRODUCTION STEPS>>

## Observed behaviour

<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

## Expected behaviour

<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

## Versions

- OS: Linux

- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

## Traceback
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by ramonski** [comment]
Senaite uses this jQuery Barcode Library: https://barcode-coder.com/en/
So yes, it should be possible to  use EAN-13 barcodes.

Please use for these kind of questions our community site: https://community.senaite.org
