### ISSUE TITLE
“Remarks” field shows raw data in the report PDF Technical

### ISSUE THREAD

**Issue by samimis97** [senaite/senaite.core#1631]
Hi, 
This is another issue ... 
https://community.senaite.org/t/remarks-field-shows-raw-data-in-the-report-pdf/554

I am a programmer but new to all this Plone/Zope ... willing to help if some one can guid me

**Comment by Espurna** [comment]
@samimis97 Thanks for reporting an issue, but this is not how issues are described. Please, follow the same pattern as others.
