### ISSUE TITLE
Report section displays date pickers in Chinese

### ISSUE THREAD

**Issue by Espurna** [senaite/senaite.core#1633]
## Description

Reports section displays date pickers in Chinese.

![image](https://user-images.githubusercontent.com/7425587/95178272-849d9580-07bf-11eb-9e7a-29e3283b5224.png)

## Reproduction guide

Go to the report section and select a date range.

## Observed behaviour

This error was fixed in https://github.com/senaite/senaite.core/pull/1570/ but it was never applied in the JS that handles "datepicker_2months".

## Expected behaviour

The widget to be displayed in the correct language:

![Selection_014](https://user-images.githubusercontent.com/7425587/95178533-d8a87a00-07bf-11eb-92c5-89d8683bb45f.png)

## Versions

- OS: Linux

- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

**Comment by ramonski** [comment]
Hi @Espurna, this error seems to be related to the jQuery UI Add-on and should be fixed when you reinstall it.
Probably skin layers in the wrong order?

**Comment by Espurna** [comment]
I think this error is the same as https://github.com/senaite/senaite.core/pull/1570/ I do not know why it is not working now but worked before :upside_down_face:
