### ISSUE TITLE
Remarks added at Sample level is showing as a script in Results report  

### ISSUE THREAD

**Issue by samimis97** [senaite/senaite.core#1651]
## Description
Remarks added at Sample level is showing as a script in Results report 
[{'content': 'Sample Remark', 'user_id': 'admin', 'user_name': '', 'id': , 'created': '2020-10-10T16:01:46+00:00'}]

## Reproduction guide
Add a remark to a sample =>publish the sample

## Observed behaviour

Remarks are showing as a script like below 
[{'content': 'Sample Remark', 'user_id': 'LabManager', 'user_name': '', 'id': , 'created': '2020-10-10T16:01:46+00:00'}]

## Expected behaviour
Remarks shows as human readable 

## Versions

- OS: Linux

- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

## Traceback
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by ramonski** [comment]
Fixed in https://github.com/senaite/senaite.impress/pull/103
