### ISSUE TITLE
Problematic misleading calculation attribution

### ISSUE THREAD

**Issue by ghost** [senaite/senaite.core#1699]
## Description

It is not possible to select more than one valid calculation in Methods, whereas multiple select should be possible. Consequently only one calculation can be selected for an analysis service whereas multiple valid ones should be selectable inherited from methods.

<img width="603" alt="Bildschirmfoto 2020-12-02 um 10 14 07" src="https://user-images.githubusercontent.com/70312626/100853148-ba8d8c00-3487-11eb-8dea-594bfcd1a4b0.png">

## Reproduction guide

- create a method trying to select multiple calculations

## Expected behaviour

<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

A common SOP includes an advice for a measurement procedure as well as properties to be observed. Upon this calculations sometimes will be defined with respect to the property. Therefore a one to many relationship is between the method and properties within a SOP (method) and the calculation has a one to one relationship with the property. Sometime calculations may be the same also for different methods, therefore it is making sense to have catalog of calculations without being attributes to a method.

**Comment by ramonski** [comment]
Implemented in https://github.com/senaite/senaite.core/pull/1719
