### ISSUE TITLE
Editing an existing worksheet template throws an error

### ISSUE THREAD

**Issue by ronna** [senaite/senaite.core#1703]
## Description

Editing an existing  Worksheet template throws an error

## Reproduction guide

Got to Setup -> Worksheet Templates and edit and existing worksheet template

## Observed behaviour

It throws an error

## Expected behaviour

You should be able to edit the worksheet template

## Versions

- OS: Linux

- senaite.core: `2.0.0rc2`
- senaite.impress: `2.0.0rc2`

## Traceback
http://172.22.164.190:8080/senaite/bika_setup/bika_worksheettemplates/worksheettemplate-1/edit?_authenticator=53bf168331ec99e5d0f02e976e7e375c614aed06

We’re sorry, but there seems to be an error…
Here is the full error message:

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 359, in publish_module
  Module ZPublisher.WSGIPublisher, line 262, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 92, in __call__
  Module Products.CMFFormController.BaseControllerPageTemplate, line 33, in _call
  Module Shared.DC.Scripts.Bindings, line 335, in __call__
  Module Shared.DC.Scripts.Bindings, line 372, in _bindAndExec
  Module Products.CMFCore.FSPageTemplate, line 256, in _exec
  Module Products.CMFCore.FSPageTemplate, line 197, in pt_render
  Module Products.PageTemplates.PageTemplate, line 85, in pt_render
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 367, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 307, in render
  Module chameleon.template, line 214, in render
  Module chameleon.template, line 192, in render
  Module 3412e09f80e237914e8d481caf03d2d1, line 1221, in render
  Module 3412e09f80e237914e8d481caf03d2d1, line 1028, in render_master
  Module b0c1c9a54e3bafd1e1ed97ad96ffd437, line 1449, in render_master
  Module b0c1c9a54e3bafd1e1ed97ad96ffd437, line 444, in render_content
  Module 3412e09f80e237914e8d481caf03d2d1, line 1013, in __fill_main
  Module 3412e09f80e237914e8d481caf03d2d1, line 183, in render_main
  Module f7129838163d50c5221d20821055e9d4, line 529, in render_body
  Module eee2dc6e4c6ac3c4b4887fe84f383d24, line 1433, in render_edit
  Module 8ca7f95e2b64a404c3b685bcf4bd858d, line 702, in render_edit
  Module eee2dc6e4c6ac3c4b4887fe84f383d24, line 1166, in __fill_widget_body
  Module zope.tales.expressions, line 250, in __call__
  Module Products.PageTemplates.Expressions, line 196, in _eval
  Module Products.PageTemplates.Expressions, line 126, in render
  Module zope.tales.tales, line 526, in length
TypeError: object of type 'listiterator' has no len()

 - Expression: "error_id"
 - Filename:   ... gg/Products/Archetypes/skins/archetypes/widgets/field.pt
 - Location:   (line 124: col 28)
 - Source:     tal:content="error_id" i18n:translate="">Validation Error</d ...
                            ^^^^^^^^
 - Expression: "field_macro | context/widgets/field/macros/edit"
 - Filename:   ... skins/bika/bika_widgets/worksheettemplatelayoutwidget.pt
 - Location:   (line 13: col 28)
 - Source:     ... se-macro="field_macro | context/widgets/field/macros/edit">
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "python:context.widget(field.getName(), mode='edit')"
 - Filename:   ... .egg/senaite/core/skins/senaite_templates/edit_macros.pt
 - Location:   (line 126: col 49)
 - Source:     ... cro="python:context.widget(field.getName(), mode='edit')" />
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "body_macro"
 - Filename:   ... 7.egg/senaite/core/skins/senaite_templates/base_edit.cpt
 - Location:   (line 90: col 35)
 - Source:     <metal:use_body use-macro="body_macro" />
                                          ^^^^^^^^^^
 - Expression: "context/main_template/macros/master"
 - Filename:   ... 7.egg/senaite/core/skins/senaite_templates/base_edit.cpt
 - Location:   (line 41: col 23)
 - Source:     ... etal:use-macro="context/main_template/macros/master"
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  template: <FSControllerPageTemplate at /senaite/base_edit used for /senaite/bika_setup/bika_worksheettemplates/worksheettemplate-1>
               modules: <Products.PageTemplates.ZRPythonExpr._SecureModuleImporter object at 0x7f56ae21cb10>
               here: <WorksheetTemplate at /senaite/bika_setup/bika_worksheettemplates/worksheettemplate-1>
               repeat: <Products.PageTemplates.engine.RepeatDictWrapper object at 0x7f569a5978c0>
               user: <PropertiedUser 'admin'>
               nothing: None
               container: <PloneSite at /senaite>
               selected_type: 'Blank'
               request: <WSGIRequest, URL=http://172.22.164.190:8080/senaite/bika_setup/bika_worksheettemplates/worksheettemplate-1/base_edit>
               traverse_subpath: []
               default: <DEFAULT>
               loop: {u'item': <Products.PageTemplates.engine.RepeatItem object at 0x7f568a5d24d0>, u'row': <Products.PageTemplates.engine.RepeatItem object at 0x7f568a5d2b10>, u'fieldset': <Products.PageTemplates.engine.RepeatItem object at 0x7f568a5c2ed0>, u'ref': <Products.PageTemplates.engine.RepeatItem object at 0x7f568a5d2bd0>, u'field': <Products.PageTemplates.engine.RepeatItem object at 0x7f568a5c2d10>}
               context: <WorksheetTemplate at /senaite/bika_setup/bika_worksheettemplates/worksheettemplate-1>
               translate: <function translate at 0x7f568b4b5750>
               root: <Application at >
               options: {'state': <Products.CMFFormController.ControllerState.ControllerState object at 0x7f568b443210>, 'args': ()}
               target_language: None
```

## Screenshot

**Comment by ramonski** [comment]
Hi @ronna, this bug was fixed here for RC3:
https://github.com/senaite/senaite.core/pull/1675

Please either use the latest source distribution to have that fixed immediately.

Please also don't forget to always re-run the upgrade step 2.0.0 in between each RC release
