### ISSUE TITLE
Bug with the Contact and CCContact field in the sample

### ISSUE THREAD

**Issue by elirabalison** [senaite/senaite.core#1735]
## Description

 On the first click, the contact dropdown shows all contacts in the system. On the second click, only contacts associated to the client appear.

## Reproduction guide

- Go to Senaite website, log in as admin 
- Go to sample and click on add button to create a new sample
- Fill client information
- Then choose contact associated with the client

## Observed behaviour

On the first click on contact or cccontact field, the contact dropdown shows all contacts in the system. On the second click, only contacts associated to the client appear

## Expected behaviour

Only contacts associated to the client must appear.

## Versions

- OS: Linux, Ubuntu 18.04

- senaite.core: 2.0.0rc2
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

## Traceback
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by ramonski** [comment]
This should be also improved by https://github.com/senaite/senaite.core/pull/2295 coming in SENAITE version 2.5.
Closing for now.
