### ISSUE TITLE
redirect

### ISSUE THREAD

**Issue by fardthakh-admin** [senaite/senaite.core#1780]
## Description

<<DESCRIPTION OF THE PROBLEM>>

## Reproduction guide

<<REPRODUCTION STEPS>>

## Observed behaviour

<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

## Expected behaviour

<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

## Versions

- OS: Linux

- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

## Traceback
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by ramonski** [comment]
Closing empty issue
