### ISSUE TITLE
Date Sampled in Samples listing has no picker

### ISSUE THREAD

**Issue by mikejmets** [senaite/senaite.core#1787]
## Description

With Sampling Enabled, Date Sampled appears the Sample list as a text field and not a date time

## Reproduction guide

In setup, enable Sampling Enabled. Create a few samples for a client and go to the Samples listing

## Observed behaviour

Date Sampled field appears as a text field

## Expected behaviour

Date Sampled should have a date time picker

## Versions

- OS: Linux

- senaite.core: `master`
- senaite.impress: `master`
- senaite.app.listing: `master`
- senaite.core.supermodel: `master`

## Screenshot
![Screenshot from 2021-03-15 13-42-18](https://user-images.githubusercontent.com/231574/111148516-64ef7200-8594-11eb-8608-61189b84f5e0.png)

**Comment by ramonski** [comment]
Implemented in https://github.com/senaite/senaite.core/pull/1788 (Thanks @mikejmets)
