### ISSUE TITLE
SamplePoint AT content type does not inherit its own Interface: ISamplePoint

### ISSUE THREAD

**Issue by faytrow** [senaite/senaite.core#1796]
## Description

The SamplePoint AT content type does not inherit its own Interface `ISamplePoint`, making the Sample Point AT content type unable to be extender or modified by 3rd party Add-Ons.

## Reproduction guide

-Create a SchemaExtender or SchemaModifier for ISamplePoint interface
-Add or Hide a schema field
-Note the change does not appear with Add-On installed

## Observed behaviour

SamplePoint AT content does not inherit its own interface `ISamplePoint`

## Expected behaviour

SamplePoint AT Content to inherit the `ISamplePoint` interface, therefore allowing schema extension and modification

## Versions

- OS: Ubuntu 20.04

- senaite.core: `2.x`

## Additional Notes

I will try to personally create the Pull Request for this soon since it's a pretty simple fix. However, I have never used the pull request feature before, so while I figure that out I wanted to make sure the issue+fix were publically available in some form.

The file that needs to be changed to correct the issue is [bika.lims.content.samplepoint.py](https://github.com/senaite/senaite.core/blob/2.x/src/bika/lims/content/samplepoint.py):

Add `from bika.lims.interfaces import ISamplePoint` to import list
Edit [line 134(135)](https://github.com/senaite/senaite.core/blob/8145fb59f916dccb1e1d005c269944ace620cd03/src/bika/lims/content/samplepoint.py#L134) from `implements(IDeactivable)` to `implements(ISamplePoint, IDeactivable)`

**Comment by ramonski** [comment]
Seems to be implemented here: https://github.com/senaite/senaite.core/blame/82c9f06dc3cbba8bb7a234ef0e609467bf52895b/src/bika/lims/content/samplepoint.py#L135
