### ISSUE TITLE
500 when attempting to add Instrument to Manufacturer

### ISSUE THREAD

**Issue by frizman21** [senaite/senaite.core#1832]
## Description

500 Error when attempting to add an Instrument to a Manufacturer

## Reproduction guide

1. Created a number of instruments
1. Created a Manufacture 'Acme'
1. Clicked on "Instruments" tab of my new manufacturue.

## Observed behaviour

![image](https://user-images.githubusercontent.com/11731079/128372985-a832967d-deb3-40b6-881a-a8536f606b0e.png)

## Expected behaviour

Ability to add instruments

## Versions

- OS: Linux

Latest Release

## Traceback
```
not available. How do I get it?
```

**Comment by ramonski** [comment]
Hi @frizman21, this is not reproducable for me, sorry.
Are there any hints in the JS console ? Maybe some instruments have special characters, so that a UnicodeDecode error occurs. Is this the latest version `2.x` you are using?

**Comment by ramonski** [comment]
closing due to no response
