### ISSUE TITLE
How to set up a dev environment?

### ISSUE THREAD

**Issue by alexleach** [senaite/senaite.core#1837]
## Description

Hello, I was hoping to set up a development environment, to try and modify some of senaite.core and potentially submit PR. I'm not very familiar with buildout, and the contributing.md file in senaite.core doesn't indicate how to set up a development environment. I've had a look through various documentation, but nowhere clearly explains how to set up such an environment.

Because senaite.core is pulled in by senaite.lims, which I don't aim to touch, this makes it particularly difficult to figure out. Where do I start?

## Versions

- OS: Linux

- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

**Comment by ramonski** [comment]
Hi @alexleach, please check https://community.senaite.org for such questions, thanks.
