### ISSUE TITLE
WS Template creation Method and instrument fields broken

### ISSUE THREAD

**Issue by Lunga001** [senaite/senaite.core#1884]
## Description
On adding or editing a worksheet template, the last item(method) on the dropdown list of the method field is selected and when chainging the method all instruments are listed instead of those that belong to the selected method.

## Reproduction guide

Add Worksheet Template 

## Observed behaviour

![Add-Worksheet-TemplateSENAITE-LIMS](https://user-images.githubusercontent.com/10023210/143041155-c9645352-a474-460d-9bd4-ae0670e7c00d.png)

## Expected behaviour

On method field Not Specified should be selected and when changed, the instrument field should have instruments that belong to the selected method
![Add-Worksheet-Template](https://user-images.githubusercontent.com/10023210/143041706-2eb2d557-675d-448b-9ebb-c73f7d441be5.png)

## Versions

- OS: Linux

- senaite.core: `2.x`

## Traceback
```
No traceback
```

**Comment by ramonski** [comment]
Hi @Lunga001,
can you check if you still have this issue with the latest version of `senaite.core`?
It should be fixed with https://github.com/senaite/senaite.core/pull/2454

**Comment by Lunga001** [comment]
Method works and as noted the user has to save the method first and then the instrument filter works.
