### ISSUE TITLE
Unable to display email and fax fields in customer views

### ISSUE THREAD

**Issue by dnota-sistemas** [senaite/senaite.core#1899]
## Description

Email and fax fields are not displayed in the customer view.

## Reproduction guide

I create a client either through the web or through the JSONAPI, and when I go to the main view of clients the fields are not shown correctly.

## Screenshot

![vista_clientes](https://user-images.githubusercontent.com/67517434/146330726-6d9c0bb0-1021-43f1-80c7-6bca5e5f8f72.png)
![cliente](https://user-images.githubusercontent.com/67517434/146330734-5e4e93a3-9c81-45e9-8a8a-378ffcd2236a.png)

**Comment by grulisco** [comment]
@ramonski @xispa This issue was solved in #2055

**Comment by ramonski** [comment]
Thanks @grulisco of bringing my attention on this one. I fixed it again in https://github.com/senaite/senaite.core/pull/2382 from side-effects of https://github.com/senaite/senaite.core/pull/2278
