### ISSUE TITLE
500 Internal server error while loading instruments in instrument types page

### ISSUE THREAD

**Issue by JosephSefara** [senaite/senaite.core#1945]
## Description

Error while loading instruments in instrument types
See the GUI and terminal console pictures

## Reproduction guide

VISIT THIS LINK http://localhost:8080/senaite5/bika_setup/bika_instrumenttypes/instrumenttype-1/instruments

## Observed behaviour

This error on the GUI.

![Screenshot from 2022-03-11 11-45-26](https://user-images.githubusercontent.com/11957102/157844427-8b3e44b9-db3d-4efc-a633-c03dd86d4e4b.png)

## Expected behaviour

Expected no errors.

## Versions

- OS: Linux

- senaite.core: `2.1.0`
- senaite.impress: `2.1.0`
- senaite.app.listing: `2.1.0`
- senaite.app.supermodel: `2.1.0`

## Traceback
```
2022-03-11 11:52:11,492 ERROR   [Zope.SiteErrorLog:252][waitress-0] 1646992331.490.516203745341 http://localhost:8080/senaite5/bika_setup/bika_instrumenttypes/instrumenttype-1/instruments/folderitems
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 371, in publish_module
  Module ZPublisher.WSGIPublisher, line 274, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module senaite.app.listing.view, line 215, in __call__
  Module senaite.app.listing.ajax, line 109, in handle_subpath
  Module senaite.core.decorators, line 20, in decorator
  Module senaite.app.listing.decorators, line 63, in wrapper
  Module senaite.app.listing.decorators, line 50, in wrapper
  Module senaite.app.listing.decorators, line 100, in wrapper
  Module senaite.app.listing.ajax, line 432, in ajax_folderitems
  Module senaite.app.listing.decorators, line 88, in wrapper
  Module senaite.app.listing.ajax, line 313, in get_folderitems
  Module senaite.app.listing.view, line 914, in folderitems
  Module bika.lims.browser.instrumenttype, line 35, in isItemAllowed
```

## Screenshot

![Screenshot from 2022-03-11 11-45-26](https://user-images.githubusercontent.com/11957102/157844427-8b3e44b9-db3d-4efc-a633-c03dd86d4e4b.png)

GUI

![Screenshot from 2022-03-11 11-46-43](https://user-images.githubusercontent.com/11957102/157844618-3660cb14-3a0e-4e49-98c0-f1ab45206f01.png)

Terminal

**Comment by ramonski** [comment]
Hi @JosephSefara,
seems like you have updated from a previous version w/o running the upgrade steps, which migrate the catalogs accordingly.
Please check if you get the same error in a vanilla SENAITE instance.
Thanks

**Comment by ramonski** [comment]
Closing due to no further activity
