### ISSUE TITLE
'getClientID' to be indexed in the 'portal_catalog' making it possible to search by  assigned client's external ID via senaite.jsonapi

### ISSUE THREAD

**Issue by Ruhanga** [senaite/senaite.core#1948]
## Description

It is currently not possible to query patients using their ClientID using from the `portal_catalog` via senaite.jsonapi which delegate to senaite.core. Say for example doing a search like `http://localhost:8080/senaite/@@API/senaite/v1/search?portal_type=Client&getClientID=some-client-id` would fail.

It would be great being able to query clients by their ClientID especially if SENAITE lims is being integrated with an external system.

**Comment by xispa** [comment]
Thanks @Ruhanga for your suggestion. Given the fact that `senaite.jsonapi`might be used differently depending on laboratory integration requirements, I think is better to make `senaite.jsonapi` be aware of searches that rely on non-existing indexes. In such case, system could fallback to filtering results by brain's metadata or, as a last resort, by object's field value. I would also make the system to log these queries, so SENAITE maintainer may consider to manually add indexes or even metadata to catalogs at a glance, without the need of adding them into `senaite.core`

**Comment by Ruhanga** [comment]
Thanks very much @xispa for the response. Would this form of manual indexing(enhancing  the brain's metadata) be possible by using  the mechanism in place to initialise senaite as [shared here](https://community.senaite.org/t/creating-an-initializer-for-senaite/788/3)?

**Comment by xispa** [comment]
Indexes and/or metadata can be directly added into existing catalogs through Zope Management Interface (ZMI), without the need of initializing anything. But yes, best approach is to create these new indexes or metadata during the initialization of your own add-on (so they are created automatically each time you activate that extension/add-on in fresh instances), in setuphandlers.py

**Comment by Ruhanga** [comment]
>Indexes and/or metadata can be directly added into existing catalogs through Zope Management Interface (ZMI)

Ohh, yes thanks for confirming the above @xispa. I had come across and actually  tried this successfully. The intention for my previous question however is confirm whether one is able to use an exported `tarball` capable of carrying the indexes with it as well as the metadata to a different fresh instance, without having to code them in an add-on or use the ZMI. Would this be possible to do @xispa?

**Comment by xispa** [comment]
Is not possible
