### ISSUE TITLE
How to use LDAP on senaite

### ISSUE THREAD

**Issue by flymaxty** [senaite/senaite.core#1974]
Hi,
Is there any way to use LDAP on senaite?
I know that plone has plone.app.ldap plugin, but how do I use it on senaite?
Is there any tutorial for it?

Thank you!

**Comment by ramonski** [comment]
If you are on Senaite 2.x you have to use https://pypi.org/project/pas.plugins.ldap/

**Comment by flymaxty** [comment]
> If you are on Senaite 2.x you have to use https://pypi.org/project/pas.plugins.ldap/

Hi @ramonski ,
Thanks for your reply!
By the way, python-ldap 3.4 is no longer support python2.x, so we need to install python-ldap=3.3.1 manually.

**Comment by ramonski** [comment]
> By the way, python-ldap 3.4 is no longer support python2.x, so we need to install python-ldap=3.3.1 manually.

Yes, we're still in the progress of migrating SENAITE to Python 3.x:

https://github.com/senaite/senaite.core/blob/2.x/P8_UPGRADE_GUIDE.md

Ramon
