### ISSUE TITLE
Issue creating worksheet with method specific template

### ISSUE THREAD

**Issue by toropok** [senaite/senaite.core#1989]
## Description

Let's say we have a worksheet template that has a specific method selected for restricting (filtering) analyses service list allowed for adding to a particular worksheet instance.

However, when you try to add a new worksheet with this fresh template it l offers you to add any unassigned analyses no matter what method it uses.

@ramonski 
do you have that behaviour too? we may offer PR if this is incorrect :)

## Reproduction guide

1. Create worksheet template with Test Method
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/14867014/165727155-22d2e167-e745-4d30-8965-517e22a1244d.png">

2. Create a new worksheet with that template 

## Observed behaviour

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/14867014/165728364-4e8a94ce-4f75-41b6-a9b3-d96f593fd7d9.png">

## Expected behaviour

filter by method

**Comment by ramonski** [comment]
Hi @toropok,
this looks incorrect to me as well, so any PR improving the WS template behavior is more than welcome!
Thanks for your contribution (also to the other guys coding with you).
Ramon

**Comment by toropok** [comment]
issue resolved thanks to everyone :) @Bugerman58 @ramonski
