### ISSUE TITLE
Fields should not be editable on Reference Definition view page

### ISSUE THREAD

**Issue by luthando5** [senaite/senaite.core#2080]
## Description

In the View page of a reference definition you are able to edit the value fields i.e expected result, min and max. You can not submit the edits.

## Reproduction guide

- Go to Senaite website and log in as admin
- Click on Setup in the top right hand corner (cogs)
- Click on Reference Definitions
- Click on any reference definition

## Observed behaviour

The reference values of the chosen reference definition can be edited but not saved on the view page.

## Expected behaviour

On the view page the user should not be able to edit any reference value.

## Versions

- OS: Linux, Ubuntu 20.04

- senaite.core: `2.x`

## Screenshot
Observed:
![image](https://user-images.githubusercontent.com/104898641/181773002-f419e3ec-a9a7-4c53-ba92-b16b8a401882.png)

Expected:
![image](https://user-images.githubusercontent.com/104898641/181773434-b4f60bd2-010a-4d96-bde4-de250239e8e5.png)

**Comment by ramonski** [comment]
Fixed in https://github.com/senaite/senaite.core/pull/2128
