### ISSUE TITLE
Typo in v02_03_000 upgrade script

### ISSUE THREAD

**Issue by Lunga001** [senaite/senaite.core#2121]
## Description

On line https://github.com/senaite/senaite.core/blob/2.x/src/senaite/core/upgrade/v02_03_000.py#L390 there is a typo and this is picked up when running the v02_03_000 upgrade script

## Reproduction guide

Run upgrade script v02_03_000 upgrade script

## Observed behaviour

Attribute error because of api.get_pat should be api.get_path

## Expected behaviour

The upgrade script to run successfully

## Versions

- OS: Linux

- senaite.core: `2.x`

## Traceback
```
'module' object has no attribute 'get_pat
```

**Comment by ramonski** [comment]
Fixed in https://github.com/senaite/senaite.core/pull/2126
