### ISSUE TITLE
KeyError help on the Sample view after receiving a Sample

### ISSUE THREAD

**Issue by Lunga001** [senaite/senaite.core#2122]
## Description
After receiving a new sample there's KeyError on the analyses table of Sample View and this may be due to https://github.com/senaite/senaite.core/pull/2101

## Reproduction guide

Add new Sample 
Received the Sample
Go to the Sample View and have a look at the Analyses Table.

## Observed behaviour

An error on the analyses table: "The server responded with the status 503: Service Unavailable"

## Expected behaviour

Analyses table should show without the 503 error

## Versions

- OS: Linux

- senaite.core: `2.x`

## Traceback
```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 371, in publish_module
  Module ZPublisher.WSGIPublisher, line 274, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module senaite.app.listing.view, line 223, in __call__
  Module senaite.app.listing.ajax, line 109, in handle_subpath
  Module senaite.core.decorators, line 22, in decorator
  Module senaite.app.listing.decorators, line 63, in wrapper
  Module senaite.app.listing.decorators, line 50, in wrapper
  Module senaite.app.listing.decorators, line 100, in wrapper
  Module senaite.app.listing.ajax, line 432, in ajax_folderitems
  Module senaite.app.listing.decorators, line 88, in wrapper
  Module senaite.app.listing.ajax, line 313, in get_folderitems
  Module bika.lims.browser.analyses.view, line 700, in folderitems
  Module senaite.app.listing.view, line 937, in folderitems
  Module bika.lims.browser.analyses.view, line 651, in folderitem
  Module bika.lims.browser.analyses.view, line 891, in _folder_item_result
KeyError: 'help'

```

## Screenshot
![image](https://user-images.githubusercontent.com/10023210/188508641-e649252c-f831-4aa9-a3a6-f3298b32d2b2.png)

**Comment by ramonski** [comment]
Hi @Lunga001,

have you updated senaite.app.listing?

<img width="557" alt="senaite core 2022-09-05 10 PM-48-25" src="https://user-images.githubusercontent.com/713193/188511241-1bb7df6f-033a-4c24-8211-b8a453543772.png">

**Comment by Lunga001** [comment]
Thank you @ramonski it works after updating  senaite.app.listing
