### ISSUE TITLE
UnknownTimeZoneError after upgrade to 2.3

### ISSUE THREAD

**Issue by toropok** [senaite/senaite.core#2159]
## Description

After update we are getting `UnknownTimeZoneError` when SENAITE tries to get object from database. What may cause it? That looks that some ARs store datetime info in a wrong way?

## Versions

- OS: Linux

- senaite.core: 2.3.0
- senaite.core.listing: 2.3.0

## Traceback
```
2022-10-07T16:34:00 ERROR ZODB.Connection Couldn't load state for bika.lims.content.analysisrequest.AnalysisRequest 0x8d6fcc
Traceback (most recent call last):
  File "/home/senaite/buildout-cache/eggs/cp27mu/ZODB-5.7.0-py2.7.egg/ZODB/Connection.py", line 780, in setstate
    self._reader.setGhostState(obj, p)
  File "/home/senaite/buildout-cache/eggs/cp27mu/ZODB-5.7.0-py2.7.egg/ZODB/serialize.py", line 634, in setGhostState
    state = self.getState(pickle)
  File "/home/senaite/buildout-cache/eggs/cp27mu/ZODB-5.7.0-py2.7.egg/ZODB/serialize.py", line 627, in getState
    return unpickler.load()
  File "/home/senaite/buildout-cache/eggs/cp27mu/pytz-2022.1-py2.7.egg/pytz/__init__.py", line 307, in _p
    return unpickler(*args)
  File "/home/senaite/buildout-cache/eggs/cp27mu/pytz-2022.1-py2.7.egg/pytz/tzinfo.py", line 539, in unpickler
    tz = pytz.timezone(zone)
  File "/home/senaite/buildout-cache/eggs/cp27mu/pytz-2022.1-py2.7.egg/pytz/__init__.py", line 188, in timezone
    raise UnknownTimeZoneError(zone)
UnknownTimeZoneError: (UnknownTimeZoneError('GMT+3',), <function _p at 0x7f4e21221ad0>, ('GMT+3',))
```

**Comment by ramonski** [comment]
Hi @toropok,
Do you use the patient add-on or any other?
Have you customized the sample view?

**Comment by ramonski** [comment]
https://github.com/senaite/senaite.core/pull/1930
https://community.plone.org/t/unknowntimezoneerror-pytz-quirks/4255

**Comment by toropok** [comment]
> 

yes we extended SamplesView with adapter:

```
class AnimalSamplesView(SamplesView):
    adapts(IListingView)
    implements(IListingViewAdapter)
```

and added couple fields to AR: sample preparation datetime and analyst who did it :) nothing special and it  worked prior to upgrade

**Comment by toropok** [comment]
> 

sorry I did not get from #1930 should wrap datetime fields while saving in some special way now to make sure it has Etc/GMT section?

**Comment by ramonski** [comment]
This should all be done by the field/widget.
Probably you just need to adapt your extended fields to use this:

```python
from senaite.core.browser.fields.datetime import DateTimeField
from senaite.core.browser.widgets.datetimewidget import DateTimeWidget
```

**Comment by toropok** [comment]
> This should all be done by the field/widget. Probably you just need to adapt your extended fields to use this:
> 
> ```python
> from senaite.core.browser.fields.datetime import DateTimeField
> from senaite.core.browser.widgets.datetimewidget import DateTimeWidget
> ```

@ramonski Thanks, it's my bad I had an oldtype  datefield object used one place and we added new feature simultaneously with Senaite version upgrade, so I make things connected wrongly :) that upgrade caused this errors somehow. 

That transmogrifier tool turned out to be tricky thing to use :) so it is definetily works, but need some time to get it run.

We used monkey-patching way (tnx @Bugerman58 ), so posting it here, may be that will help somebody:

**1. /src/senaite/your-add-on/monkeys/configure.zcml**
```
<configure  xmlns="http://namespaces.zope.org/zope" xmlns:monkey="http://namespaces.plone.org/monkey">
...

  <!-- Register our patch method -->
  <monkey:patch
    description="patch UnknownTimeZoneError"
    class="pytz"
    original="timezone"
    preserveOriginal="True"
    replacement=".pytz_patch.timezone" />
...
</configure>

```

**2. /src/senaite/your-add-on/monkeys/pytz_patch.py**

```python
from senaite.your-add-on.config import logger

import pytz


def timezone(zone):
    if zone:
        # see: senaite.core.api.dtime.get_timezone
        # convert DateTime `GMT` to `Etc/GMT` timezones
        # NOTE: `GMT+1` get `Etc/GMT-1`!
        if zone.startswith("GMT+0"):
            zone = zone.replace("GMT+0", "Etc/GMT")
        elif zone.startswith("GMT+"):
            zone = zone.replace("GMT+", "Etc/GMT-")
        elif zone.startswith("GMT-"):
            zone = zone.replace("GMT-", "Etc/GMT+")
        elif zone.startswith("GMT"):
            zone = zone.replace("GMT", "Etc/GMT")
    else:
        zone = "Etc/GMT"

    if hasattr(pytz, "_old_timezone"):
        try:
            return pytz._old_timezone(zone)
        except Exception as err:
            logger.error("Error call _old_timezone function - {}".format(str(err)))
    return pytz.UTC
```
