### ISSUE TITLE
All QC Sample ID are same cross worksheet for version 2.4.0+

### ISSUE THREAD

**Issue by erikking** [senaite/senaite.core#2289]
## Description

When I want to import lab data (2d-csv format) for one worksheet with reference sample, the reference sample value cannot be importd whatever the reference sample ID / name in csv file.

So I checked Home -> Setup -> Suppliers -> Reference Samples -> Analyses, and found all QC sample ID are same cross worksheets.

## Reproduction guide

1. add supplier
2. add reference sample
3. create multiple worksheets and add the reference sample above
4. check QC sample IDs in Home -> Setup -> Suppliers -> Reference Samples -> Analyses

## Observed behaviour

For version 2.4.0, 2.4.1, 2.5.0, I got following QC Sample ID
![image](https://user-images.githubusercontent.com/7684990/230635722-d2201e27-768d-46cb-a0bd-5beefd009b30.png)

## Expected behaviour

For version <= 2.3.0
![image](https://user-images.githubusercontent.com/7684990/230636136-6031b886-ad94-4f05-8749-7f10301ee454.png)

## Versions
2.4.0+

**Comment by ramonski** [comment]
Hi @erikking,
Can you share your ID Server configuration?
Thanks

**Comment by erikking** [comment]
Thanks for you response @ramonski , 

![image](https://user-images.githubusercontent.com/7684990/230724848-ba55318c-e4e3-4bcd-80b5-d5325285bb56.png)

I used same ID server config for different version.

And for version 2.4.0 +, the ID server values referencesample-ECS always = 1 after add reference sample in worksheet.

**Comment by ramonski** [comment]
Your split length must be 2, then it should work.

**Comment by ramonski** [comment]
Ah, apologies, I was looking at the generated ID `ECS-001-001` with the two dashes.
We will try to reproduce this issue according to your description to see what is going on there.
Thanks.

**Comment by erikking** [comment]
Thanks a lot for your quick response. My ultimate goal is to import lab result file for worksheet with reference sample. For version 2.3.0, I can use reference sample ID `ECS-001-007` with lab value for worksheet `WS-020` in imported csv file for the example above, then importing works well and the reference sample lab value will show in worksheet page, but when I upgrade to 2.4.0+, I cannot find a way to import reference sample lab value.

**Comment by erikking** [comment]
Hi @ramonski 
I did further investigation in source code about the the issue, I found ReferenceAnalysesGroupID do not change when add new reference control in worksheet. And a potential cause may be related ReferenceAnalysesGroupID generation function `nextRefAnalysesGroupID`  in [worksheet](https://github.com/senaite/senaite.core/blame/v2.4.0/src/bika/lims/content/worksheet.py). 
Could you help to check with that?

**Comment by erikking** [comment]
Hi @ramonski 
I thought I figured it out, there may two cause

- in line 435 `ids = [int(i.split(prefix)[1]) for i in ids if i and rr.match(i)]` the ids always return emtpy
- in line 415 `ref_analysis.reindexObject(idxs=["getWorksheetUID", "getAnalyst"])` need add getReferenceAnalysesGroupID to build the index because `nextRefAnalysesGroupID ` function call the index to get distinct count of reference analyses group

Hope it helps.

**Comment by erikking** [comment]
And also the ReferenceAnalysesGroupID is same for duplication as well in worksheet

**Comment by ramonski** [comment]
Thanks @erikking for pointing out the code!
We will check this as soon as possible to find which fix is needed to make this work properly.
Best regards, Ramon

**Comment by ramonski** [comment]
Fixed in https://github.com/senaite/senaite.core/pull/2388

**Comment by erikking** [comment]
Very nice to hear it got fixed. 👍

**Comment by xispa** [comment]
Please @erikking close this issue after you double check. Thanks

**Comment by erikking** [comment]
Sure, sorry for the late close.
