### ISSUE TITLE
Senaite Bar code generation with clientId

### ISSUE THREAD

**Issue by mboubekeur** [senaite/senaite.core#2316]
## Description
Hi
I`m new for using senaite. After a successful installation, the process  requires hide the client name which means print a bar code using clientId.
<<DESCRIPTION OF THE PROBLEM>>
I affect to batch the variable B-{clientID}-{seq:03d}
## Reproduction guide

<<REPRODUCTION STEPS>>
When i confirm everything looks ok.
## Observed behaviour
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 288, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module Products.ATContentTypes.tool.factory, line 498, in __call__
  Module ZPublisher.mapply, line 85, in mapply
  Module ZServer.ZPublisher.Publish, line 44, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 92, in __call__
  Module Products.CMFFormController.BaseControllerPageTemplate, line 30, in _call
  Module Products.CMFFormController.ControllerBase, line 233, in getNext
  Module Products.CMFFormController.Actions.TraverseTo, line 38, in __call__
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module Products.CMFFormController.FSControllerPythonScript, line 104, in __call__
  Module Products.CMFFormController.Script, line 145, in __call__
  Module Products.CMFCore.FSPythonScript, line 134, in __call__
  Module Shared.DC.Scripts.Bindings, line 335, in __call__
  Module Shared.DC.Scripts.Bindings, line 372, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 349, in _exec
  Module script, line 1, in content_edit
   - <FSControllerPythonScript at /senaiteORGM/content_edit used for /senaiteORGM/batches/portal_factory/Batch/batch.2023-05-30.9036101868>
   - Line 1
  Module Products.CMFCore.FSPythonScript, line 134, in __call__
  Module Shared.DC.Scripts.Bindings, line 335, in __call__
  Module Shared.DC.Scripts.Bindings, line 372, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 349, in _exec
  Module script, line 12, in content_edit_impl
   - <FSPythonScript at /senaiteORGM/content_edit_impl used for /senaiteORGM/batches/portal_factory/Batch/batch.2023-05-30.9036101868>
   - Line 12
  Module Products.Archetypes.BaseObject, line 679, in processForm
  Module bika.lims.content.batch, line 154, in _renameAfterCreation
  Module bika.lims.idserver, line 545, in renameAfterCreation
  Module bika.lims.idserver, line 514, in generateUniqueId
KeyError: 'clientID'

<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>
The error affects creating a batch with desired parameters
## Expected behaviour
Creating a batch with desired parameters

<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

## Versions

- OS: Linux Debian 10

- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

## Traceback
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by mikejmets** [comment]
Those variables is case sensitive, try using clientId

**Comment by ramonski** [comment]
Indeed, here are the variables listed:
https://github.com/senaite/senaite.core/blob/2.x/src/senaite/core/idserver/idserver.py#L234-L240
