### ISSUE TITLE
Additional cc-contacts not working

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#2380]
## Description

In client contacts you can set additional client-contacts, that should also receive reports always.
Those cc-contacts should be applied on every add sample task as default.

## Reproduction guide

Setup a client contact with additional `Contacts to CC`.

Try to add a sample with this contact.

## Observed behaviour

After choosing the primary contact the field `Contacts to CC` remains empty.

## Expected behaviour

After choosing the primary contact the configured `Contacts to CC` should appear automatically.

## Versions

- senaite.core: `2.5`

## Screenshot

![Screenshot_20230907_141126](https://github.com/senaite/senaite.core/assets/25460329/bbdc706b-b358-4121-9d9d-bf895dab55d7)

**Comment by ramonski** [comment]
Fixed in #2385
