### ISSUE TITLE
Analyses not sorted in Transposed Multiresult Form

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#2404]
## Description

Transposed Multiresult Form (which is very cool indeed) has been introduced with #2400.
Unfortunately analyses are not sorted yet in the correct manner

## Reproduction guide

Create a batch with samples containing with a defined set of analyses, e.g. with the analysis profile `Trace Metals`.
After reception mark the samples, click button `Multi Results` and compare 'classic' view with 'transposed' view.

## Observed behaviour

Analyses in the transposed view are not ordered correctly, somehow erratic, see screenshot.

## Expected behaviour

Analyses in the transposed view are sorted in the expected order like in the classic view.
Preferably they should be sorted by analysis category and analysis sort key as used in most views.

## Screenshot
![grafik](https://github.com/senaite/senaite.core/assets/25460329/7f570ab2-cc15-4029-8569-3e376fd63036)

**Comment by ramonski** [comment]
Fixed in https://github.com/senaite/senaite.core/pull/2407
