### ISSUE TITLE
Interims missing in Transposed Multiresult Form

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#2405]
## Description

Transposed Multiresult Form (which is very cool indeed) has been introduced with https://github.com/senaite/senaite.core/pull/2400.
Unfortunately interim values aka result variables are not displayed, therefore the form is not functional for calculated analyses.

## Reproduction guide

Create, receive sample with an analysis service that uses a calculation and interims, e.g. Moisture 

## Observed behaviour

Interims missing in transposed view

## Expected behaviour

Interims are displayed int transposed view

## Screenshot
![grafik](https://github.com/senaite/senaite.core/assets/25460329/41ce43bf-aec6-4a52-8f37-cc9f896a764f)

**Comment by ramonski** [comment]
Fixed in https://github.com/senaite/senaite.core/pull/2406
