### ISSUE TITLE
Calculating datetime differences in Senaite (Bika) calculations appears to be problematic

### ISSUE THREAD

**Issue by RML-IAEA** [senaite/senaite.core#2446]
How should I handle datetime in Senaite calculations?
![senaite calculation date problem](https://github.com/senaite/senaite.core/assets/95472242/b26bc4bc-b545-4b10-9dea-075efd3af681)

**Comment by grulisco** [comment]
Hi @RML-IAEA: What is the problem here? Does the example above work or not?
BTW better ask configuration questions at https://community.senaite.org

**Comment by RML-IAEA** [comment]
Hi **[grulisco](https://github.com/grulisco)**, "It doesn't work at all. Datetime is not accepted in Senaite calculations

**Comment by grulisco** [comment]
Hi @RML-IAEA; I do not know how your datetime functions are working exactly. If the result of the expression is a string, it should work IMO.
Alternatively you can setup almighty "external calculations", see https://www.senaite.com/docs/analysis-calculations#external-calculations

**Comment by RML-IAEA** [comment]
It only accepts float or integer values, not strings.

**Comment by grulisco** [comment]
Don't know then. Maybe your date result isn't a string yet.

We're working with calculated string expressions successfully.

Basically an entry like `"This is a string"` as calculation formula should return this string as result.

We have several cases like `"This string" if [condition] else "Other string"`.

**Comment by RML-IAEA** [comment]
How can you calculate the difference in days between datetimes inside the Senaite calculations section?

**Comment by grulisco** [comment]
see https://github.com/senaite/senaite.core/issues/2446#issuecomment-1852231401

**Comment by grulisco** [comment]
Simple datetime calcs work; try e.g. calculating number of days waiting for chrismas:
`(datetime(2023,12,24)-datetime.today()).days`

So the problem seems converting datetime data in a proper way.
