### ISSUE TITLE
app.listing search_box encoding issue (CoffeeScript)

### ISSUE THREAD

**Issue by toropok** [senaite/senaite.core#2500]
Hi,

Due that there is no "issue" section in `senaite.app.listing` project I'll post it here.

I've encountered with some unexpected behaviour.

When user types into the search-box component of `app.listing` Cyrillic string and submit search request. The string has being encoded to UTF-8 suddenly.

<img width="907" alt="Screenshot 2024-02-22 at 18 20 09" src="https://github.com/senaite/senaite.core/assets/14867014/6527be93-a6f1-48a8-a8f0-117c603b0465">

Further the Python part encodes it again and return as the response.

Seems that response change the state of the component and it's re-renders and resubmit request with non-encoded text (and search performs fine).

<img width="907" alt="Screenshot 2024-02-22 at 18 22 01" src="https://github.com/senaite/senaite.core/assets/14867014/e3edce39-ee54-4a55-9819-6548dab7e346">

Because non-cyrillic text always perform just on request.

We're failed to figure out where the encoding in CoffeeScript happened :) please help where to look that mystical thing

**Comment by ramonski** [comment]
Hi Leonid, does this cause a problem, so that it does not work?

I guess the issue is related to the functionality that preserves some of the filter/sorting criteria as request parameter and reads it out again here:

https://github.com/senaite/senaite.app.listing/blob/2.x/src/senaite/app/listing/view.py#L702-L709

The magic that does this is located here:

https://github.com/senaite/senaite.app.listing/blob/2.x/webpack/app/listing.coffee#L272-L283

Hope that helps for the beginning.

**Comment by ramonski** [comment]
Well, it might also be related to this part that causes the encoding:

https://github.com/senaite/senaite.app.listing/blob/2.x/webpack/app/listing.coffee#L117

where the `get_url_parameter` is here:

https://github.com/senaite/senaite.app.listing/blob/2.x/webpack/app/api.coffee#L44-L60

**Comment by toropok** [comment]
Aha, well initially we noticed that "Show more" button in the `senaite.app.listing` component doesn't work at all if filter parameter set as non-latin string.

our investigation led us to the fact that string encodes by browser and this causes this condition assert as true:
https://github.com/senaite/senaite.app.listing/blob/2dcccb044cb3f497c64ee96ab7b98ff3816e77af/webpack/app/listing.coffee#L2164

In this code statement encoded value assigns to State and leads to reload.
 
We'll add PR to fix that.

**Comment by toropok** [comment]
[Fix 141](https://github.com/senaite/senaite.app.listing/pull/141)

posted PR

**Comment by toropok** [comment]
btw same happens to German or Spanish letter as well like in: Übel or bebé

**Comment by ramonski** [comment]
Thanks for fixing the übel bug!😄
