### ISSUE TITLE
Worksheet print templates sorting feature

### ISSUE THREAD

**Issue by toropok** [senaite/senaite.core#2513]
hi

A customer hardly uses custom worksheet print templates for analysts daily routine support. Now there is no way to rearrange elements of dropdown templates menu:

<img width="1061" alt="image" src="https://github.com/senaite/senaite.core/assets/14867014/3c14248c-01ed-43dd-8478-f3dbbc300ab4">

First, would you mind if we commit the PR which store templates order as SENAITE registry record similar to "worksheet columns order"? I just want to make it sure it does not contradict your intentions?

And extra question is it makes sense to add slecting dropdown menu element directrly to worksheet layout:

<img width="1705" alt="Screenshot 2024-03-12 at 12 49 31" src="https://github.com/senaite/senaite.core/assets/14867014/0224fbed-59f9-4d77-8769-817a63eb9579">

**Comment by ramonski** [comment]
Hi Leonid,

I initially planned to move these WS templates completely to `senaite.impress`.

Technically, it would be already possible by calling the `publish` view either directly on the context itself, or by passing in request parameters, e.g. `https://.../ws-0001?template=my.lims:WorksheetDefaultTemplate.pt&orientation=landscape&paperformat=A4`.

However, for the time being, you are welcome to provide the PR with a new registry record to select the default print template or change/filter the available templates in the registry.

Regarding your second question: Maybe best you override this functionality check if you can also select the template with a request parameter?
