### ISSUE TITLE
Objects are indexed in multiple catalogs

### ISSUE THREAD

**Issue by rockfruit** [senaite/senaite.core#349]
The following objects, indexed in the following multiple catalogs.  This will be slow, and it should not be required, however there may be code that mistakenly relies on this behaviour, so it should be removed carefully.

```
Batch                 bika_catalog, portal_catalog
Sample                bika_catalog, portal_catalog
SamplePartition       bika_catalog, portal_catalog
ReferenceSample       bika_catalog, portal_catalog
Department            bika_setup_catalog, portal_catalog
AnalysisService       bika_setup_catalog, portal_catalog
SampleType            bika_setup_catalog, portal_catalog
SamplePoint           bika_setup_catalog, portal_catalog
StorageLocation       bika_setup_catalog, portal_catalog
Instrument            bika_setup_catalog, portal_catalog
InstrumentType        bika_setup_catalog, portal_catalog
InstrumentLocation    bika_setup_catalog, portal_catalog
Method                bika_setup_catalog, portal_catalog
Calculation           bika_setup_catalog, portal_catalog
AnalysisProfile       bika_setup_catalog, portal_catalog
ARTemplate            bika_setup_catalog, portal_catalog
LabProduct            bika_setup_catalog, portal_catalog
LabContact            bika_setup_catalog, portal_catalog
Manufacturer          bika_setup_catalog, portal_catalog
ReferenceDefinition   bika_setup_catalog, portal_catalog
SRTemplate            bika_setup_catalog, portal_catalog
Supplier              bika_setup_catalog, portal_catalog
WorksheetTemplate     bika_setup_catalog, portal_catalog
```

**Comment by xispa** [comment]
Indeed, we'll need to go into detail on this. Bear in mind https://github.com/senaite/bika.lims/pull/252 , a PR (to be reviewed once we finish with this integration stuff) that creates a catalog only for Samples.

**Comment by ramonski** [comment]
Current catalog mappings can be found here: https://github.com/senaite/senaite.core/blob/master/bika/lims/setuphandlers.py#L93
But agree, we can remove them from `portal_catalog`

**Comment by ramonski** [comment]
It seems like DX contents are always indexed in `portal_catalog`.
I think this won't be much of an issue as long as we keep `portal_catalog` small and probably drop more of the unused indexes of this catalog, e.g. comments etc.

Related PR is https://github.com/senaite/senaite.core/pull/1872
