### ISSUE TITLE
AR/Sample Navigation Viewlet

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.core#350]
## Steps to reproduce

Add multiple ARs to a client

## Current behavior

There is no "easy" way to navigate between the ARs/Samples

## Expected behavior

There is a next/previous navigation viewlet which allows to navigate to the next item within a view

## Screenshot (optional)

<img width="118" alt="nav" src="https://user-images.githubusercontent.com/713193/32389879-859aebaa-c0cc-11e7-923d-795180ad4ca7.png">

**Comment by grulisco** [comment]
beautiful 👍

**Comment by Espurna** [comment]
Can this enhancement be closed? @ramonski 

Is this issue related to lists or inside an object (Sample)?

![Selection_017](https://user-images.githubusercontent.com/7425587/57284133-dc0e7200-70b0-11e9-88e8-44a6c18d0ee0.png)

**Comment by ramonski** [comment]
This would be inside Samples, but yes, let's close this, I won't have time for this in the near future...
