### ISSUE TITLE
DateTime Widget does not display the Time 

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.core#471]
## Steps to reproduce

- Add `show_time=True` to a `DateTimeWidget`
- Display the edit mode of the widget

## Current behavior

No Time and no Timezone is displayed.

## Expected behavior

At least the time should be there

## Link to Code

https://github.com/senaite/bika.lims/blob/master/bika/lims/browser/widgets/datetimewidget.py#L26

**Comment by ramonski** [comment]
From Gitter:

Ramon Bartl @ramonski 16:28
I was wondering why my extended DateTime field did not show the time, even if I added the property show_time=True to the widget, and found this piece of code:
https://github.com/senaite/bika.lims/blob/master/bika/lims/browser/widgets/datetimewidget.py#L26
Why do we read here the value from the _properties dict instead of the widgets’ attribute?

**Comment by rockfruit** [comment]
@ramonski you're right, that was meant to read from self, not self._properties.
