### ISSUE TITLE
Calculated results not marked for submission if zero

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#476]
I encountered a similar problem to https://github.com/bikalims/bika.lims/issues/1978.
All entries trigger calculation, even zero. But if the **result** is zero, the service is not marked for submission.
In then end the service will be probably missed and its calculation will never be triggered again.

## Steps to reproduce
Create an AR with a calculated service, e.g. TotalHardness in senaite demo.
Of course my example in the screenshot is pure nonsense in reality, but shows the problem.

## Current behavior
If the last manual entry triggers the calculation of TotalHardness **and** if the result is equal to zero the service is not marked.

## Expected behavior
In any case the service is marked after calculation.

## Screenshot (optional)
![grafik](https://user-images.githubusercontent.com/25460329/34081841-41eb9e36-e354-11e7-93e5-0007b59264ca.png)

**Comment by rockfruit** [comment]
"javascript" <3

false
