### ISSUE TITLE
Calculation does not keep the order of Interim fields, rather sorted alphabetically by keyword

### ISSUE THREAD

**Issue by xispa** [senaite/senaite.core#483]
#### 1. Create a Calculation "Cloro libre" with these interims:
 
Keyword | Field Title | Default value | Unit
------- | ----------- | ------------- | ----
V0 | Vol | 100.0 | mL 
C3 | c[Cl2] | | mmol/L
V3 | Vol (NH4)2Fe(SO4)2·6H2O | | mL
V5 | Vol Mn+ | | 0.0 | mL

And with this calculation formula:
```
([C3]*([V3]-[V5]))/[V0]
```

#### 2. Once saved, interim fields are sorted alphabetically:

Keyword | Field Title | Default value | Unit
------- | ----------- | ------------- | ----
C3 | c[Cl2] | | mmol/L
V0 | Vol | 100.0 | mL 
V3 | Vol (NH4)2Fe(SO4)2·6H2O | | mL
V5 | Vol Mn+ | | 0.0 | mL

## Current behavior

Calculation does not preserve the order of the interim fields, rather sort them alphabetically by keyword. Thus, interim fields are sorted wrongly in manage results view and analyses lists.

## Expected behavior

Calculation preserves the order in which the interim fields were entered by the user and they appear in that order in manage results view and analyses lists.

**Comment by lemoene** [comment]
Also see https://community.senaite.org/t/order-of-interim-fields-on-wss-and-ar-results-tabs/41 re Dry Matter

![image](https://user-images.githubusercontent.com/1196034/39422031-fa8fcd74-4c6b-11e8-8ce8-681b9f472b83.png)

I also notice that when spread over 2 Categories, Interim _As Is_ gets duplicated

![image](https://user-images.githubusercontent.com/1196034/39421971-bf8a6a9a-4c6b-11e8-8a7e-6d8d69afb10c.png)

**Comment by ramonski** [comment]
<img width="1235" alt="cloro libre" src="https://user-images.githubusercontent.com/713193/40279285-16ae9db2-5c40-11e8-80fe-127e06206a51.png">
