### ISSUE TITLE
Sampler does not get saved for AR Sampling in Batch

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#500]
I'll follow up and edit here, to see whether this also happens outside batches

**Edit** Is ok outside Batches

## Steps to reproduce

Sampling on

Create new ARs in a Batch and after completing the Date Sampled and Sampler fields, _Sample_ them from the _To be Sampled_ AR list inside the batch

![image](https://user-images.githubusercontent.com/1196034/34361557-d222a1b8-ea73-11e7-90e0-9a0033ac6fec.png)

## Current behavior

The ARs progress the next state _Sample due_, but the Sampler is not saved

![image](https://user-images.githubusercontent.com/1196034/34361587-0cbd5958-ea74-11e7-851b-af649ce287cb.png)

## Expected behavior

Sampler name to be saved

**Comment by lemoene** [comment]
I notice that the Sampler is save now, but still gets the GetSampler error (in the demo)

![image](https://user-images.githubusercontent.com/1196034/34620416-1539786e-f24e-11e7-98bb-a29bc98c6ad9.png)

The sticker printing error interestingly occurs only  during auto-printing at _Receive_. I stepped through all the different formats.

Traceback (most recent call last):
  File "/home/bika/bikalims/src/senaite.core/bika/lims/browser/stickers.py", line 271, in renderItem
    return embed(self)
  File "/home/bika/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/bika/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/bika/buildout-cache/eggs/five.pt-2.2.4-py2.7.egg/five/pt/engine.py", line 98, in __call__
    return self.template.render(**kwargs)
  File "/home/bika/buildout-cache/eggs/z3c.pt-3.0-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/bika/buildout-cache/eggs/Chameleon-3.1-py2.7.egg/chameleon/zpt/template.py", line 289, in render
    return super(PageTemplate, self).render(**_kw)
  File "/home/bika/buildout-cache/eggs/Chameleon-3.1-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/bika/buildout-cache/eggs/Chameleon-3.1-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "0bdee5ddb77ee59312d79a7864fdbf61.py", line 150, in render
AttributeError: 'NoneType' object has no attribute 'getSampler'

 - Expression: "python:sample.getSampler()"
 - Filename:   ... /bika/lims/browser/templates/stickers/Code_128_1x48mm.pt
 - Location:   (line 26: col 14)
 - Source:     sampler           python:sample.getSampler();
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  modules: 
               sample: 
               ar: 
               container: 
               wrapped_repeat: 
               portal_url: https://senaite.ridingbytes.com
               traverse_subpath: 
               partnr: 006
               template: 
               translate: 
               repeat: {...} (0)
               views: 
               args: 
               here: 
               part: 
               user: 
               nothing: 
               ar_id: 
               default: 
               request: 
               item: 
               loop: {...} (0)
               context: 
               portal_state: 
               view: 
               root: 
               options: {...} (0)
               target_language: 

When I access the sticker from its icon, all formats render fine

![image](https://user-images.githubusercontent.com/1196034/34620793-657a7688-f24f-11e7-8eb6-0d0e412911b3.png)

**Comment by lemoene** [comment]
Persists in 1.2.2 and perhaps need higher prioritisation? Blocks Batch use

**Comment by xispa** [comment]
Fixed as per https://github.com/senaite/senaite.core/pull/672
