### ISSUE TITLE
Sampler field is compulsory when Sampling workflow is on

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#508]
## Steps to reproduce

In a system with **_Sampling enabled_**,  navigate to AR lists containing _To be Sampled ARs_, both

i) inside a Batch

ii) outside Batches

Select ARs without completing the Sampler field and _Sample_, in case ii:

![image](https://user-images.githubusercontent.com/1196034/34354545-b3e9ae4e-ea37-11e7-84f2-f11d63db8b18.png)

## Current behavior

i) The user is returned to the same page without the ARs being promoted to Sampled or any message

ii) The AR is _Sampled_ by the LIMS, sans the Sampler field being completed

![image](https://user-images.githubusercontent.com/1196034/34354596-2c1d77f6-ea38-11e7-99a3-8751a9ff4361.png)

## Expected behavior

The Sampler field in the lists should default the user logged in, in GLP, it is the Sampler himself.

If the user _Samples_ the AR without the Sampler field being completed, the system should display a message "Sampler is required for the Sampling transition" or some such.

The ARs should not transition, and stay in _To be Sampled_ state

**Comment by xispa** [comment]
I cannot reproduce. If I select an Analysis Request in `sample_due` state and with no Sampler selected and press the button "Sample", the system does nothing (neither the Analysis Request nor  Sample are transitioned to `sampled`) and the message "Info - No changes made." appears at the top of the list, see screenshot below:

![sampling](https://user-images.githubusercontent.com/832627/35105973-ec7bbbd2-fc64-11e7-8328-da18dc2929d8.png)

I agree the message should be more informative, created [Message too generic when trying to sample an AR w/o a Sampler assigned #584](https://github.com/senaite/senaite.core/issues/584)

If the user belongs to the group of "Samplers", the list defaults to the user logged in already. Be sure your user belongs to that group:

![sampelr](https://user-images.githubusercontent.com/832627/35107099-faf01584-fc67-11e7-92f9-2db045697551.png)
