### ISSUE TITLE
Worksheets: Clicking on the Listing header renders the page inside the page again

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.core#522]
## Steps to reproduce

Browse to an WS with assigned analyses and click on the listing table header

## Current behavior

The entire site get rendered inside the existing page

## Expected behavior

The listing is sorted correctly

## Screenshot (optional)

<img width="1885" alt="ws-001_ _bika" src="https://user-images.githubusercontent.com/713193/34456424-fab71ca6-ed95-11e7-8c5b-ea3bddd6b5d3.png">

**Comment by lemoene** [comment]
Got that too (once) now when following tracking another bug to do with the WS Search parameter filters, could be related. Logging separately

**Comment by ramonski** [comment]
This one actually works and is not reproducable anymore. Probably fixed with https://github.com/senaite/senaite.core/pull/646
