### ISSUE TITLE
Dormant Analysis Services displayed in AR Templates

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#524]
Could be related to https://github.com/senaite/bika.lims/issues/518

## Steps to reproduce

Create a new AR Template

## Current behavior

Dormant AS Calcium is offered for selection

![image](https://user-images.githubusercontent.com/1196034/34457369-5df2b2a0-edb7-11e7-981c-cc1a0ab27077.png)

![image](https://user-images.githubusercontent.com/1196034/34457374-84c460d6-edb7-11e7-8e2a-54fed1e161e3.png)

## Expected behavior

Dormant ASs should not be offered for selection

**Comment by ramonski** [comment]
Should be fixed with https://github.com/senaite/senaite.core/issues/783

**Comment by ramonski** [comment]
Still not working for new Profiles. I think the fix done here: https://github.com/senaite/senaite.core/pull/786 should be made as well inside this view.

<img width="1277" alt="analyseprofil hinzufugen senaite 2018-04-25 10-42-25" src="https://user-images.githubusercontent.com/713193/39235145-691de97e-4875-11e8-93d4-1745743bfdf7.png">
