### ISSUE TITLE
Partition configuration widget on AR Templates fails

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#525]
## Steps to reproduce

Add a new AR Template and configure its Partitions, e.g.

## Current behavior

The Partition tab opens with first Partition titled _part-1_ by default which users want to edit because of its effect on IDs, P1, P2 rather

![image](https://user-images.githubusercontent.com/1196034/34457449-1489497e-edb9-11e7-8f87-eb2efa8da87a.png)

Editing the field, 

![image](https://user-images.githubusercontent.com/1196034/34457467-cf45fa32-edb9-11e7-9545-0aa5083b67c8.png)

it resets to _part 1_ when the user adds another partition

![image](https://user-images.githubusercontent.com/1196034/34457476-f2186126-edb9-11e7-9633-702d595b117b.png)

Going back to edit it, empties its other fields too. Eventually it takes effect, but not friendly

Workaround seems to be to open the two partition rows first

## Expected behavior

The first partition should allow edits to its title and not reset when the user opens a new one

**Comment by xispa** [comment]
With the new partitioning system, these `part-n` ids are only used to make the assignment of analyses to partitions easier in the Template view. These identifiers are not used anywhere else.

Related: https://github.com/senaite/senaite.core/pull/1068 , https://github.com/senaite/senaite.core/pull/1192 and https://github.com/senaite/senaite.core/pull/1199
