### ISSUE TITLE
Images and Barcodes not printed in reports

### ISSUE THREAD

**Issue by Nihadness** [senaite/senaite.core#538]
## Steps to reproduce
Go to any AR and try to print a sticker.
## Current behavior
Although stickers are rendered in HTML format properly, PDF files miss the 'barcode' section.
## Expected behavior
PDF files displays barcodes as well.

**Comment by ramonski** [comment]
Relevant PR https://github.com/senaite/senaite.core/pull/539

**Comment by ramonski** [comment]
Please note, the reason why we not accepted yet https://github.com/senaite/senaite.core/pull/539 is that we would like to find a solution to avoid the extra requests from WeasyPrint, where we need to inject the authentication header and the `__ac` cookie to authenticate it against the system.

**Comment by ramonski** [comment]
## Virtual Host Monster Setup

- Add this line to your `/etc/hosts` file: `127.0.0.1 senaite.dev`
- Go to the `virtual_hosting` tool in the Zope ZMI root, e.g. http://localhost:8080/virtual_hosting
- Add this mapping in the "Mappings" Tab: `senaite.dev/senaite` (Assuming your Plone site is called `senaite`)
- Browse to http://senaite.dev:8080

<img width="1131" alt="vhm" src="https://user-images.githubusercontent.com/713193/34650923-4aedd474-f3c9-11e7-9eef-d580d0572166.png">

**Comment by ramonski** [comment]
The WeasyPrint URL Fetcher receives now an URL like this: http://senaite.dev:8080/logo_print.png

To get the physical path within the site, we can do something like this:
```python
>>> request = api.get_request()
>>> request.physicalPathFromURL(url)
['', 'senaite', 'logo_print.png']
```

The current request is authenticated, so it should be possible to get the object directly:

```python
>>> portal = api.get_portal()
>>> path = "/".join(request.physicalPathFromURL(url))
>>> portal.restrictedTraverse(path, None)
<FSImage at /senaite/logo_print.png>
```

The challenge now is to get the image data from these objects, which might be an Attachment, a FSImage or maybe an ATImage.

**Comment by ramonski** [comment]
The return value of the WeasyPrint URL fetcher needs to be a dictionary like this:

```python
{
    'encoding': None,
    'file_obj': <addinfourl at 4572827016 whose fp = <socket._fileobject object at 0x110902650>>,
    'filename': None,
    'mime_type': 'image/png',
    'redirected_url': 'http://senaite.dev:8080/logo_print.png'
}
```

Not sure about the interface that `file_obj` needs to provide, probably only `read` which would make a `StringIO` object a good choice.

**Comment by ramonski** [comment]
The docstring of the `default_url_fetcher` function tells us this regarding the return values:
```python
def default_url_fetcher(url):
    """Fetch an external resource such as an image or stylesheet.

    Another callable with the same signature can be given as the
    :obj:`url_fetcher` argument to :class:`HTML` or :class:`CSS`.
    (See :ref:`url-fetchers`.)

    :type url: Unicode string
    :param url: The URL of the resource to fetch.
    :raises: An exception indicating failure, e.g. ``ValueError`` on
        syntactically invalid URL.
    :returns: A dict with the following keys:

        * One of ``string`` (a byte string) or ``file_obj``
          (a file-like object)
        * Optionally: ``mime_type``, a MIME type extracted e.g. from a
          *Content-Type* header. If not provided, the type is guessed from the
          file extension in the URL.
        * Optionally: ``encoding``, a character encoding extracted e.g. from a
          *charset* parameter in a *Content-Type* header
        * Optionally: ``redirected_url``, the actual URL of the resource
          if there were e.g. HTTP redirects.
        * Optionally: ``filename``, the filename of the resource. Usually
          derived from the *filename* parameter in a *Content-Disposition*
          header

        If a ``file_obj`` key is given, it is the caller’s responsibility
        to call ``file_obj.close()``.
    """
```

Passing in the byte string should be therefore sufficient.

**Comment by ramonski** [comment]
Until now I found 3 different objects to handle:

1. File System Images, e.g. '/senaite/logo_print.png' 
2. Zope Browser Resources, e.g. /senaite/++resource++bika.lims.images/AccreditationBodyLogo.png'
3. Attachment, e.g. '/senaite/clients/client-1/attachment-2/AttachmentFile' 

Probably there are more and all of those objects have a different interface to fetch the `filename`, `mime_type` and `file_data`.

I think that was the place where I stopped at my first approach and used the `url_fetcher`. Any ideas are welcome...

**Comment by ramonski** [comment]
The current provided PR uses now [Plone Subrequest](https://github.com/plone/plone.subrequest) to fetch the data directly. Also see: https://pypi.python.org/pypi/plone.subrequest

This bypasses the need to hack the authentication into the request or fetch the file data by hand, e.g. from an Attachment.

**Comment by xispa** [comment]
Thanks!, added the last comment in the PR
