### ISSUE TITLE
Sampler field is not displayed in Analysis Request Add form

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#546]
Logging this in case it is a bug, was done for Bika Water ' LIMS potentially before the cut. Else it needs to go on his list of migration items.

Some labs capture the _Sampler_ field on the AR Create form before (not using Scheduled Sampling).

## Steps to reproduce

On AR Create page, attempt to add _Sampler_ as field to the AR Create form, 
https://senaite.ridingbytes.com/analysisrequests/ar_add_manage

## Current behavior

Sampler is not available?

## Expected behavior

To be able to add the Sampler field to (and used it on) the AR Create form

![image](https://user-images.githubusercontent.com/1196034/34650995-acbf83ba-f3d2-11e7-9c14-b67cd2f061b2.png)

**Comment by xispa** [comment]
Fixed as per #561 , but please note the Sampler field will only be displayed when the setting "Enable Sampling" in "Setup > Sampling and coc" is checked.

**Comment by lemoene** [comment]
Damn, we need to have the Sampler field on the form also if Sampling is disabled @xispa... to eliminate the transition (still capturing Sampler, Date Sampled and Field Analyses)

could swear it was addressed somewhere

Let us know @rockfruit whether we can let this hang till you are done. needed for ALS

**Comment by lemoene** [comment]
@mikejmets we resolved this for Cannabis, maybe we can implement that first? Am targeting a (final) visit to them first week of April, staying till they are done
