### ISSUE TITLE
Client Batch lists are empty

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#548]
## Steps to reproduce

Be sure to have some batches that were created containing a specified client's ARs only

![image](https://user-images.githubusercontent.com/1196034/34654046-82a0b294-f3fe-11e7-9543-ffa3668b7506.png)

Then Navigate to that Client's own Batch list, 

![image](https://user-images.githubusercontent.com/1196034/34654068-bd0aa3b8-f3fe-11e7-982f-6b8b7fe2fb57.png)

## Current behavior

The Client's Batch list is empty

## Expected behavior

The Client's Batches to be listed

![image](https://user-images.githubusercontent.com/1196034/34654093-1c3bb962-f3ff-11e7-9013-c1743aac1c4c.png)

**Comment by ramonski** [comment]
Works now, thanks @xispa ;)

<img width="1615" alt="hh-batches" src="https://user-images.githubusercontent.com/713193/34827929-11e699ca-f6dc-11e7-9649-b152800e044f.png">

**Comment by lemoene** [comment]
Much appreciated, thanks. We also have Witek for 4 - 6 weeks to help speed migration and fixes up
