### ISSUE TITLE
AR Templates do not create Partitions' Preservations

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#549]
## Steps to reproduce

Create an AR using an AR Template including more than one Partition, each with its own Preservation

![image](https://user-images.githubusercontent.com/1196034/34663560-177c097a-f460-11e7-80b1-acc1fe9db777.png)

## Current behavior

The Preservation is not written to the Partitions created. The _Security Seal Intact_ Boolean is checked for the first partition, but not the second.

![image](https://user-images.githubusercontent.com/1196034/34663643-6b4bc22a-f460-11e7-9601-670fe3a194c4.png)

![image](https://user-images.githubusercontent.com/1196034/34663694-aed231a0-f460-11e7-85b4-617ca583f8bb.png)

## Expected behavior

The Preservations for the Partitions to be created too. Not sure but think the _Security Seal Intact_ is checked by default.

**Comment by xispa** [comment]
Superseded by https://github.com/senaite/senaite.core/pull/1068 , https://github.com/senaite/senaite.core/pull/1192 and https://github.com/senaite/senaite.core/pull/1199
