### ISSUE TITLE
Instalation error: WeasyPrint==0.42 - invalid enviroment marker: python_version <3.0

### ISSUE THREAD

**Issue by Radd78** [senaite/senaite.core#560]
Hello,
During buildout of client error error:
Setup script exited with error in WeasyPrint setup command: Invalid environment marker: python_version < "3.0"
An error occurred when trying to install WeasyPrint 0.42. Look above this message for any errors that were output by easy_install.

Python ver 2.7

**Comment by ramonski** [comment]
Hello @Radd78

Installing SENAITE via buildout should only be used for development, because it usually has too many side-effects depending on the installed Python modules, used Python version, Operating System, Permissions etc.

Please download therefore the turn-key ready Ubuntu VM from http://senaite.com.

Thanks and best regards
Ramon

**Comment by ramonski** [comment]
Just as an additional note. This error occured because of the `setuptools` version you are using. Please do a  `python bootstrap.py` which should give you a newer `setuptools` version:

```bash
$ ../python2.7/bin/python bootstrap.py
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
[...]
``` 

And then re-run buildout:

```bash
$ bin/buildout -v
```

**Comment by Radd78** [comment]
Thank You very much

**Comment by danxfisher** [comment]
@ramonski :

Tagging along on this, what are the recommendations for a production install?  I'm assuming it's slightly different from a dev install and not using the turn-key VM (as the docs specifically say it's not for production).

Thanks!

**Comment by ramonski** [comment]
Hi @danxfisher, you can check out our Ansible Playbook here:

https://github.com/senaite/senaite.ansible-playbook

With this Playbook you can basically configure your production VM the right way (and with strong passwords).

However, some manual settings inside the VM usually remain and this is why we also offer the VM as a custom product to our clients.

If you have further question you are also welcome to join our Gitter Chatroom:
https://gitter.im/senaite/Lobby
