### ISSUE TITLE
ValueError: year=1000 is before 1900 on AR View

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.core#565]
## Steps to reproduce

Browse to a published AR

## Current behavior

Traceback occurs in the background:

```
Error converting '1000/01/01 00:00:00 GMT+0' time to string in <AnalysisRequest at 17-00049-R1>.
2018-01-12 09:21:14 WARNING Bika Traceback (most recent call last):
  File "/home/bika/bikalims/src/senaite.core/bika/lims/browser/__init__.py", line 88, in ulocalized_time
    time_str = _ut(time, long_format, time_only, context, 'bika', request)
  File "/home/bika/buildout-cache/eggs/Products.CMFPlone-4.3.15-py2.7.egg/Products/CMFPlone/i18nl10n.py", line 205, in ulocalized_time
    mapping[key] = time.strftime('%' + key)
  File "/home/bika/buildout-cache/eggs/DateTime-3.0.3-py2.7.egg/DateTime/DateTime.py", line 1551, in strftime
    microseconds).strftime(format)
ValueError: year=1000 is before 1900; the datetime strftime() methods require year >= 1900
```

## Expected behavior

No Traceback occurs

## Screenshot (optional)

--

**Comment by xispa** [comment]
@Nihadness this one fails into your realm

**Comment by ramonski** [comment]
The fixed DateTimePicker does fix the issue for new values, but I get still tracebacks for existing ARs with the old data. Maybe we can fix that in `ulocalized_timetime_str`? Leaving that one open.

**Comment by xispa** [comment]
Or maybe (I think it would be better), sanitize ARs with old data with an upgrade step

**Comment by ramonski** [comment]
yes, that might be better. However, the server is at the moment relying on the JS validator, which is IMO never a good idea.

So there should be indeed a migration and maybe a server side validator as well.

**Comment by ramonski** [comment]
Closing this one for now, since I've not seen the issue anymore in recent installations
