### ISSUE TITLE
'Assigned to WS' indication on AR Lists

### ISSUE THREAD

**Issue by Lunga001** [senaite/senaite.core#570]
## Steps to reproduce

A manager navigates to the AR lists looking for unassigned ARs -he/she clicks the 'Unsassigned'      icon. Issue copied from https://jira.bikalabs.com/browse/BC-288

## Current behavior

The user gets to see a cluttered list, they'd generally only be interested in Received and Due ARs

## Expected behavior

It could be an option to include a column showing the Assigned icon next to ARs (Due, Received) as  we had in earlier versions, but that could be performance pricey. An easier way, could be to only include Due and Received ARs the Unassigned listing?

**Comment by Lunga001** [comment]
**Proposed solution.**
@mikejmets  was proposing that we put a setting on Bika Setup, where a user can be able to set which states appear there. Where a person can be able to choose a list of applicable states.

**Comment by xispa** [comment]
Duplicates [Assigned Icon on AR Lists #520](https://github.com/senaite/senaite.core/issues/520). This is a feature request, there is no need to create an issue for this, better open a Pull Request directly.
