### ISSUE TITLE
Multipage PDF-Reports with bad footer position

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#581]
## Steps to reproduce
- Create an AR with several ASs and Comments to force at least one page break
- Publish AR with default settings
- (Footers in HTML-Preview are rendered correctly)

## Current behavior
The position of footers in the resulting PDF-File is different on every page, see example.
In fact the actual offset is totally arbitrary depending on the amount of content and can differ in both directions.
I observed the same problem in our customized report (under development).
This is not really publishable to clients.

## Expected behavior
Footers in PDF-Report are aligned correctly on every page.

## Screenshot (optional)
![snapshot](https://user-images.githubusercontent.com/25460329/35067691-02ce5880-fbd5-11e7-8f38-39aa0787d857.png)

[example_footer.pdf](https://github.com/senaite/senaite.core/files/1640632/example_footer.pdf)

**Comment by grulisco** [comment]
Tried to add a screenshot too, but doesn't work - don't know why, sorry...

**Comment by ramonski** [comment]
Closing in favor of the soon coming `senaite.publisher` add-on
