### ISSUE TITLE
Add Pango as dependency to Readme

### ISSUE THREAD

**Issue by vito80ba** [senaite/senaite.core#589]
## Steps to reproduce
Just add "senaite.lims" to the eggs

## Current behavior
The installation breaks with errors cause Pango is a dependency

## Expected behavior
Installation works fine

**Comment by ramonski** [comment]
@vito80ba: Thanks for reporting.

Did you install the system dependencies as listed here: https://github.com/senaite/senaite.ansible-playbook/blob/master/vars/Ubuntu.yml?

However, we do not track individual setup problems in this tracker and recommend to use the turnkey ready VM from http://senaite.com

**Comment by vito80ba** [comment]
Hi ramonski.
I follow the "classic way" to install Plone add-on. As also described in the README of "senaite.lims",
I always use the "dev mode" on my mac so I skipped the "ubuntu guide" / ansible tool.
Maybe you could add just a row to the readme file with the "pango dependency" :)

**Comment by ramonski** [comment]
Actually it is not possible to add Pango as a dependency in `setup.py`, see here:
```
Couldn't find index page for 'Pango' (maybe misspelled?)
Getting distribution for 'Pango>=1.29.3'.
Couldn't find index page for 'Pango' (maybe misspelled?)
```

**Comment by ramonski** [comment]
Ok, changed title to match the expected outcome. We want to have a line in the readme, similar to here: http://weasyprint.readthedocs.io/en/stable/install.html

**Comment by vito80ba** [comment]
great :)

**Comment by ramonski** [comment]
All dependencies are listed here: https://www.senaite.com/docs/installation#install-system-dependencies
