### ISSUE TITLE
WS Create. Template Analyses to be filtered by Client

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#632]
Not sure whether this missed the switchover, is in Bika Water which I think Campbell religiously merged with Bika LIMS trunk

Many labs need to apply WS Templates per client, and this made it possible

## Steps to reproduce

Create a new WS, on neither the Initial or secondary pages is it possible to apply a Client filter for WS Templates

## Current behavior

![image](https://user-images.githubusercontent.com/1196034/35813597-b3be53b8-0a9c-11e8-84ac-56a1068de40a.png)

![image](https://user-images.githubusercontent.com/1196034/35813631-c3bdadea-0a9c-11e8-97c9-c47e54860d25.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/1196034/35813682-e1e6777a-0a9c-11e8-8ec0-49743b244a36.png)

![image](https://user-images.githubusercontent.com/1196034/35813729-00c23008-0a9d-11e8-9aea-6046293059d5.png)

**Comment by ramonski** [comment]
Corrected labels

**Comment by ramonski** [comment]
Will be resolved in Version 1.3 as follows:

A searchbox is provided for the assignable Analyses.
This allows to search for a Client name and sorting by Analysis. Or searching for a category and sorting by client.

<img width="1583" alt="ws-001 senaite 2018-11-23 12-33-39" src="https://user-images.githubusercontent.com/713193/48941525-28f3f700-ef1c-11e8-8d3f-6fddead71fb1.png">

This makes it also possible to search for template

<img width="1591" alt="worksheets senaite 2018-11-23 12-37-05" src="https://user-images.githubusercontent.com/713193/48941666-c94a1b80-ef1c-11e8-8538-e8db8ecdd10e.png">
