### ISSUE TITLE
AR Create form does not assign configured Analysis Specification

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#643]
## Steps to reproduce
Create a New AR for a Client that has a Specification selected, e.g

![image](https://user-images.githubusercontent.com/1196034/36060846-fe6a0310-0e59-11e8-9706-7e6a1fb41868.png)

![image](https://user-images.githubusercontent.com/1196034/36060857-4fa1858c-0e5a-11e8-90f0-a7db39f6fd81.png)

Lab is set to the same
![image](https://user-images.githubusercontent.com/1196034/36060866-83ec2aea-0e5a-11e8-9a08-18b257a59729.png)

## Current behavior

The Spec is not auto-captured on the AR Create form

![image](https://user-images.githubusercontent.com/1196034/36060892-09e643ce-0e5b-11e8-95b8-2459b20728a3.png)

**Edit. Or applied for the An**

![image](https://user-images.githubusercontent.com/1196034/36066547-14e1ff94-0eb4-11e8-8ed3-3567908a4486.png)

## Expected behavior

The Analsyis Spec from to be completed as configured

## Side issue

Analysis Specs needs a revisit for normalisation - Termed _Named Specs_ at some point it means that there can be more than one Spec per Sample Type, e.g Import Standards for the US and Europe. 

Named Specification _US Import 18_ and _EU/Asia/Africa import 2020_ may differ for a Sample Type _Steel_ say. Later

**Comment by ramonski** [comment]
Seems like this is a duplicate of https://github.com/senaite/senaite.core/issues/601?

**Comment by lemoene** [comment]
duplicate

**Comment by ramonski** [comment]
Which of those Specs should be auto-selected in the AR Add form when more than one Spec exists for a Sample Type, e.g. for "Wheat"?  There is no possibility for the user to set that.

**Comment by lemoene** [comment]
Soemwhere i explained that An Specs has to be normalised properly. Best now is to go with a simplified case of Sample Type based Specs only, in 95% od the cases it'll be the lab's.

Consider going with just that until a sponsor can be found?

I'll have a look on the demo in a while to see whether that works

**Comment by lemoene** [comment]
Stripped out Sample Type duplicates

![image](https://user-images.githubusercontent.com/1196034/36194416-3539eb7e-1172-11e8-8ace-161c69df1dbf.png)

On Client Preferences, only Sample Type Lab and Client should then show. 
That and the AR create form seems to list them OK on a proper configuration, e.g. wheat

![image](https://user-images.githubusercontent.com/1196034/36194622-17113d5e-1173-11e8-9a41-f022ee2bf0b6.png)

however, some issues remain, have to be logged separately at soonest opportunity

Client specs pref selection

* note that the AR based specs were done away with (on the AR form at least) imo should go completely
![image](https://user-images.githubusercontent.com/1196034/36194663-49b19ace-1173-11e8-85c2-9935cb7accbe.png)

* ditto allowing spec edits on the AR form

![image](https://user-images.githubusercontent.com/1196034/36194695-7471b38e-1173-11e8-9d5b-6a41f35a52f6.png)

* Deactivated specs are listed for selection on AR Create form

![image](https://user-images.githubusercontent.com/1196034/36194770-b554233c-1173-11e8-8cd2-79c6ff740429.png)


![image](https://user-images.githubusercontent.com/1196034/36194815-e3a94636-1173-11e8-95b8-677a42ea09d1.png)
