### ISSUE TITLE
Completely remove 'Editable' Analysis Specifications

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#665]
Am editing for clarity at https://github.com/senaite/senaite.core/issues/601, and am breaking this one out. Needed a the link already for reference there

I was under the impression  'Editable Analysis Specifications' were removed during the AR Create form refactoring for performance improvements already. Only sponsors DBW (many Specs) probably ever used it properly, some research labs showed interest, and it can be removed for simplicity's sake and decluttering too

## Steps to reproduce, Current behavior

The so-called AR's own Specs is still available as a set-up option

![image](https://user-images.githubusercontent.com/1196034/36328089-8579d830-1369-11e8-812c-bc19696a7491.png)

Also as Client preference

![image](https://user-images.githubusercontent.com/1196034/36328316-55c6b8d2-136a-11e8-837b-f91699452db8.png)

And on the AR Create form, the Specs are still editable too

![image](https://user-images.githubusercontent.com/1196034/36328293-44c06f4c-136a-11e8-91dd-c0c7efc26f74.png)

## Expected behavior

'Analysis Request Specifications' as Specs option should be removed

The Spec fields should not be editable on the AR Create, in fact can be removed?

**Comment by ramonski** [comment]
AR Specs can be since the change to AR Add (and before) be deactivated with this setup setting:

<img width="1263" alt="setup senaite 2018-02-17 12-48-17" src="https://user-images.githubusercontent.com/713193/36340597-163e72fa-13e1-11e8-8e26-5301653ea227.png">

<img width="915" alt="happy hills senaite 2018-02-17 12-50-36" src="https://user-images.githubusercontent.com/713193/36340601-2d728952-13e1-11e8-9221-9d542ac2bd0c.png">

Hence, there is no need to remove them in code.

The option "Default AR Specifications" is completely useless as stated already in https://github.com/senaite/senaite.core/issues/601 and will be therefore removed.

**Comment by lemoene** [comment]
phew, apologies I completely did not see that option...

re #601 _"Default AR Specifications" is completely useless_, you mean the _'Editable AR Specifications'_  i think, tagged _Enable AR Specifications_  in you screenshot

Default 'AR Specifications' eg per Sample Type (lab) is critical. But can be dropped from AR Create in this round, and applied automatically to all New ARs if Analysis Specifications are on in the Setup, I just noticed there isn't such an option. Low priority

![image](https://user-images.githubusercontent.com/1196034/36340878-042ae8de-13ee-11e8-8720-e9708938eb4d.png)

![image](https://user-images.githubusercontent.com/1196034/36340925-fb1b3798-13ee-11e8-8ac2-aa96d5e4ccec.png)

**Comment by lemoene** [comment]
And to clear the mud further, they should be called _**Analysis Specifications**_, they are applied to Analysis results.

![image](https://user-images.githubusercontent.com/1196034/36340958-8470dd5e-13ef-11e8-9d8d-6f375179a09e.png)

![image](https://user-images.githubusercontent.com/1196034/36341001-0f2dfb70-13f0-11e8-9146-a6f4bad24507.png)

is correct in the Setup

![image](https://user-images.githubusercontent.com/1196034/36341014-51d17c4a-13f0-11e8-8fb5-173cd1ed7afb.png)

shall I copy pasta this to a separate issue?
