### ISSUE TITLE
Transition buttons not displayed on AR Lists

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#667]
**Edit, Title** was _Sample, Receive buttons not displayed on To be Sampled, Due AR Lists_

## Steps to reproduce

Navigate to AR lists in the demo - in a Batch, Client or the global AR list

## Current behavior

The Sample Button is only displayed on the '_Active_' lists, and not on the '_To be Sampled_' lists

![image](https://user-images.githubusercontent.com/1196034/36339661-6a2afacc-13d3-11e8-9c5f-c0fa61b70ed0.png)

![image](https://user-images.githubusercontent.com/1196034/36339634-c6ece730-13d2-11e8-9c34-437a136cc41d.png)

## Expected behavior

The Sample button to be displayed and active on the _To be Sampled_ AR lists - its logical home. IMO high on the list of 1 percenters, saving clicks - users come here and normally just select _All_ and click _Sample_, more so in batch processing

**Comment by lemoene** [comment]
oh dear, neither _Receive_ on _Due_ lists

![image](https://user-images.githubusercontent.com/1196034/36339715-5e4cc4a0-13d4-11e8-9a6d-3838e2887fbd.png)

**Comment by ramonski** [comment]
Better test please.

<img width="849" alt="analysis requests senaite 2018-02-17 12-23-19" src="https://user-images.githubusercontent.com/713193/36340450-6e78e2f6-13dd-11e8-99b3-d317c85cbfa0.png">


<img width="1573" alt="analysis requests senaite 2018-02-17 12-26-10" src="https://user-images.githubusercontent.com/713193/36340475-c7c64d3a-13dd-11e8-857b-84e8c2b0bdbf.png">

**Comment by lemoene** [comment]
hard refreshed, back, thanks
