### ISSUE TITLE
Editing of batch labels impossible

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#691]
## Steps to reproduce
- Go to setup/batch labels
- click on an existing batch label

## Current behavior
At senaite.ridingbytes.com error message:

`<zope.traversing.namespace.view object at 0x7f4c62493a10>
`

At our own testmachine: Insufficient Privileges (even as admin)

## Expected behavior
Editing batch label

**Comment by ramonski** [comment]
Looks like a duplicate of https://github.com/senaite/senaite.core/issues/590

**Comment by xispa** [comment]
Indeed. a duplicated of #590 . Closing

**Comment by grulisco** [comment]
@xispa or @juangallostra: Please reopen issue, as it is again a problem after latest update of our test instance by @ramonski.
