### ISSUE TITLE
Object log of analyses missing

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#692]
## Steps to reproduce
- Go to any published or verified AR
- Click on a single analysis

## Current behavior
Nothing happens

## Expected behavior
Object log of analyses pops up

(tested on senaite.ridingbytes.com and own instance)

**Comment by ramonski** [comment]
Fixed with https://github.com/senaite/senaite.core/pull/1161

<img width="1275" alt="h2o-0001-r01 senaite 2018-12-14 21-00-10" src="https://user-images.githubusercontent.com/713193/50024621-48de7e00-ffe3-11e8-833e-3c6fa316d1fd.png">
