### ISSUE TITLE
Missing images on the client side in published HTML reports

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#704]
## Steps to reproduce
LIMS setup in an intranet, where only the lab personnel has access. 
Publish an AR to a client contact, that shall receive an e-mail (EMail and/or PDF selected).

## Current behavior
Client receives in each case a HTML-rendered email with results, but images cannot be loaded.
This will confuse clients,even when they get the PDF too.
This is not avoidable by deselecting "Email" in the contact's setting.

## Expected behavior
- Email in contact's setting actually means HTML rendered result report. Images as an important part should be embedded.
- At least, If only PDF is selected, the e-mail body should not contain the HTML-report, but a short note guiding to the attached PDF.

**Comment by xispa** [comment]
You added the images in the AR itself (via "Add Attachment") or you added them through the Results Interpretation field?

**Comment by grulisco** [comment]
Images were added via AR/Add Attachment, but this issue addresses other graphical elements within the HTML report as well:
- Laboratory Logo
- Accreditation Logo
- accredited Marker (similar to :star:)

**Comment by ramonski** [comment]
I think this was related to the WeasyPrint URL fetcher and the SSL certificate.
Closing this, also in favor of the upcoming `senaite.publisher`
