### ISSUE TITLE
Analysis Request Error: maximun recursion depth excedeed whilecalling a Python object

### ISSUE THREAD

**Issue by didinsson** [senaite/senaite.core#713]
## Steps to reproduce
I'm using Senaite in test for my lab. Senaite is intallied in a Ubuntu 16.04, Plone 4.3.14 ans Senaite Core 1.2.3. The machine was a Core I5, 4G RAM and 1Tera of DD.

## Current behavior
While I tried registrate a Analysis Request, not save, and appear this message in the Analysis Request form:

    Error: maximun recursion depth excedeed whilecalling a Python object  (Image 1.png)

For this request I'm using a Analysis Request Template and Especification Analisis. (image 2.png and 3.pdf). The Analysis Request not registration, with a number, but appear a code saved (Image 4.png). The sample is registrated with a code normally.

Additional, the system not generating a Trace Back for this error. This error not appear in Bika Lims with the same data for AR.

Regards...!!!

## Screenshot (optional)
![1](https://user-images.githubusercontent.com/25927747/37111000-8f2b0898-220c-11e8-9b6e-91073598beb3.png)
![2](https://user-images.githubusercontent.com/25927747/37111015-9a52ce0e-220c-11e8-8410-641e6ec1f2d6.png)
![4](https://user-images.githubusercontent.com/25927747/37111025-9f5a5994-220c-11e8-8310-47bdb5f6834c.png)
[3.pdf](https://github.com/senaite/senaite.core/files/1790412/3.pdf)

**Comment by ramonski** [comment]
Thanks for reporting. Can it be that you specified calculations which have a circular dependency?
E.g. that Analysis A depends via a calculation on Analysis B, and Analysis B has a calculation assigned that depends on calculation A?

**Comment by ramonski** [comment]
Please also post the output from the terminal here, thanks.

**Comment by ramonski** [comment]
Hi @didinsson, thanks for coming back on this. Could you however please describe the case more precise, so that we can add some code to handle such cases more gracefully.
Please also put the Traceback into this issue, so that we can see where the recursion happens.
Thanks in advance
