### ISSUE TITLE
Barcodes not generating

### ISSUE THREAD

**Issue by chavooo** [senaite/senaite.core#728]
## Steps to reproduce

1. Place AR Request
2. Generate Label
3. Print Label

## Current behavior

Barcodes not generating on stickers

## Expected behavior

Barcodes should generate on stickers

## Screenshot (optional)

Senaite Version:
SENAITE LIMS 1.2.0

Host OS:
Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-693.21.1.el7.x86_64
Architecture: x86-64

Client OS: 
macOS Sierra 10.12.6 

Browser Version:
Chrome Version 64.0.3282.186

Resulting Sticker Screenshot:
![screen shot 2018-03-13 at 8 11 25 am](https://user-images.githubusercontent.com/37116117/37352611-e4a88a06-269a-11e8-950b-cb91708e29ff.png)

JS Console Screenshot:
![screen shot 2018-03-13 at 8 41 09 am](https://user-images.githubusercontent.com/37116117/37352572-ccadab7a-269a-11e8-8205-b6f5592b937c.png)

WeasyPrint error I noticed from client1 event.log:

> 2018-03-13T11:37:08 ERROR weasyprint Failed to load image at "data:image/bmp;base64,Qk12CAAAAAAAADYAAAAoAAAAsAAAAAwAAAABABgAAAAAAEAIAAATCwAAEwsAAAAAAAAAAAAA////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////" (Could not load GDK-Pixbuf. PNG and SVG are the only image formats available.)

**Comment by ramonski** [comment]
Aat a first glance this seems like a deployment issue you have here. You’re probably accessing the site via HTTPS and your domain name, e.g. https://my-lims.local does not match with the self-signed certificate you have
So probably this will not happen if you access the site w/o HTTPS

**Comment by chavooo** [comment]
@ramonski 

I access the site without HTTPS, but same issue:

![screen shot 2018-03-13 at 9 20 31 am](https://user-images.githubusercontent.com/37116117/37354969-1806cb56-26a0-11e8-8197-638fc25a5bbf.png)

**Comment by ramonski** [comment]
That's unexpected. Do you also encounter the same issues in your JS Console? Can you please "hard refresh" your site by holding the SHIFT key and clicking on the reload button? Thanks

**Comment by chavooo** [comment]
Issues disappeared from the console, but the weasyprint error in the event log still persists:

![screen shot 2018-03-13 at 9 33 22 am](https://user-images.githubusercontent.com/37116117/37355831-ea340502-26a1-11e8-8a31-6e6156d297c5.png)

> 2018-03-13T12:29:11 ERROR weasyprint Failed to load image at "data:image/bmp;base64,Qk12CAAAAAAAADYAAAAoAAAAsAAAAAwAAAABABgAAAAAAEAIAAATCwAAEwsAAAAAAAAAAAAA////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////////////////////////////////////////////AAAAAAAA////AAAA////////AAAA////////////////AAAA////////////AAAA////////////AAAAAAAA////AAAA////AAAAAAAAAAAA////////////AAAAAAAA////AAAA////////////AAAA////AAAAAAAA////////////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////AAAAAAAA////////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAA////////AAAAAAAA////AAAAAAAAAAAA////////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAA////////AAAAAAAAAAAA////////AAAAAAAA////AAAAAAAAAAAA////AAAAAAAAAAAA////AAAAAAAA////AAAAAAAA////////////AAAAAAAAAAAA////AAAA////AAAAAAAA////////////////////////////////////////" (Could not load GDK-Pixbuf. PNG and SVG are the only image formats available.)

**Comment by ramonski** [comment]
Ok, the last line (Could not load GDK-Pixbuf. PNG and SVG are the only image formats available.) looks anyhow like a deployment issue. Please make sure you installed all requirements listed here:
https://github.com/senaite/senaite.ansible-playbook/blob/master/vars/Ubuntu.yml
or use the Ansible Playbook to create your server machine.

**Comment by chavooo** [comment]
I built and installed gdk-pixbuff from source and restarted plone which resolved the issue:

```
wget https://ftp.gnome.org/pub/gnome/sources/gdk-pixbuf/2.36/gdk-pixbuf-2.36.11.tar.xz
tar xf gdk-pixbuf-2.36.11.tar.xz
cd gdk-pixbuf-2.36.11
./configure --prefix=/usr --without-libtiff
make
make install
ldconfig /usr/lib
bin/plonectl restart
```
I'm running CentOS so there were a few extra things I had to do to get Plone and Senaite up and running.

The following may work as well:
```
yum install gdk-pixbuf2.x86_64
```
