### ISSUE TITLE
Traceback when submitting an Analysis Request with ReportDryMatter enabled

### ISSUE THREAD

**Issue by xispa** [senaite/senaite.core#731]
## Steps to reproduce

1. Go to an Analysis Request Add view and fill the required fields
2. Choose "Moisture" and "Dry Matter" analyses
3. Check the field "Report As Dry Matter" and submit
4. Receive the Analysis Request
5. Go to Manage results
6. Introduce results for analysis "Moisture" and Submit

## Current behavior

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.analysisrequest.workflow, line 61, in __call__
  Module bika.lims.browser.analysisrequest.workflow, line 387, in workflow_action_submit
KeyError: 'ResultDM'
```

## Expected behavior

The system submits the analyses as usual, with no Traceback.
Suggestion: remove dry matter functionality. I guess it can be achieved by making use of calcs already.

**Comment by juangallostra** [comment]
Related https://github.com/senaite/senaite.core/issues/767

@xispa should we proceed to delete the Dry Matter functionality?

**Comment by ramonski** [comment]
+1 for removing this functionality. This should make the AR Add form also more performant

**Comment by lemoene** [comment]
easy now..., at minimum we need an indication from AR Create form how the results must be reported on the COA, it is not always enabled and differs per AR, and it also effects prices

could well do the actual Dry Matter calcs using the standard machinery, we'll have to check that out first

**Comment by lemoene** [comment]
note @Lunga001

**Comment by lemoene** [comment]
Breaking out to see whether DM, the calc, can be handled in the calcs engine. hope to report back here real soon. say 1 hour

**Comment by lemoene** [comment]
thinking on the fly @juangallostra , leaving the Dry Matter AS selection in the setup empty or set to _none_ ( by labs not using DM reporting) could remove the option from AR Create?

**Comment by lemoene** [comment]
Forcing the DM Calc through the standard calculation engine could work like this (just that I don't know whether it helps much fro where it is needed)

In the setup, select a **_Dry Matter Calculation_** in stead of an Analysis

![image](https://user-images.githubusercontent.com/1196034/39116082-cb053e14-46e3-11e8-82f0-760c7acb18cd.png)

If left empty/_none_ disable DM on AR Create form

When in use, the AR create form maintains the current option to _Report as Dry Matter_ per new AR and 

- The selected DM Calculation's dependent An is included on the AR, e.g. Moisture is just forced in with an accompanying message only

- ensures the the DM values are used on the COA and all results views (i thnk currently in brackets just after 'As is' values

It breaks however in the Dry Matter calculation itself as it is something like 

_[RawResult] * 100 / (100 - [Moisture]_

Unless we have [RawResult] readily available, the labs will have to create a formula for each AS, e,g

_[Arsenic] * 100 / (100 - [Moisture]_
... through to ;-)
_[Zinc] * 100 / (100 - [Moisture]_

And then compounds

Over to you guys, please keep me in the loop

**Comment by lemoene** [comment]
What are we left with after _Dry matter functionality is removed from SENAITE as suggested and discussed_ @juangallostra ?

**Comment by lemoene** [comment]
Which discussion?-)

I think it appropriate to convey the predicament and uneasiness of Quantum Analytics with the approach taken in removing such an integral part of their system. They sponsored Inkosi Bika LIMS 2 and without their assistance and mentorship over the past decade, none of us would've been here.
