### ISSUE TITLE
Interim fields not created for QC Analyses on WSs

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#735]
## Steps to reproduce

Create and Receive ARs that include Calculated results. Have Reference Samples ready for them too. Then Create a WS that include both routine and control calculated results

## Current behavior

Interim fields are not created for the control Analysis and its results field is open for editing

In this example note that the Calculation is made up of Interim fields only with no dependencies on other Analyses

![image](https://user-images.githubusercontent.com/1196034/37403548-d9d36aa8-2797-11e8-9f4c-2806e9af3c7c.png)

## Expected behavior

Calculated Control Analyses be displayed like their routine cousins, with Interim fields and result itself not manually editable (calculated only)

![image](https://user-images.githubusercontent.com/1196034/37403682-54d1dd7a-2798-11e8-9b5a-b5be78c42359.png)

**Comment by Lunga001** [comment]
![untitled 1](https://user-images.githubusercontent.com/10023210/37767339-78615f8c-2dd2-11e8-95be-39099c5d01e1.jpg)
Hi @xispa, please see the diagram. I was wondering if we should either move the InterimFields and Calculation fields (and related methods) from AbstractRoutineAnalysis to AbstractAnalysis or reparent ReferenceAnalysis to a child from AbstractRoutineAnalysis
