### ISSUE TITLE
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory

### ISSUE THREAD

**Issue by phillip-toone** [senaite/senaite.core#739]
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory

I attempt to install senaite.core on a new Ubuntu 16.04 server according to the instruction provided in the README.md as follows:

```
apt update
apt install -y python-setuptools python-dev build-essential libssl-dev libxml2-dev libxslt1-dev libbz2-dev libjpeg62-dev libz-dev
apt install -y libreadline-dev wv poppler-utils
apt install -y git
wget --no-check-certificate https://launchpad.net/plone/4.3/4.3.15/+download/Plone-4.3.15-UnifiedInstaller.tgz
tar -xf Plone-4.3.15-UnifiedInstaller.tgz
cd Plone-4.3.15-UnifiedInstaller
./install.sh standalone
cd /usr/local/Plone/zinstance
echo "[buildout]" | tee senaite.cfg
echo "index = https://pypi.python.org/simple" | tee -a senaite.cfg
echo "extends = buildout.cfg" | tee -a senaite.cfg
echo "[instance]" | tee -a senaite.cfg
echo "eggs +=" | tee -a senaite.cfg
echo "    senaite.core" | tee -a senaite.cfg
sudo -u plone_buildout bin/buildout -c senaite.cfg
```
This generates the following error:
```
Getting distribution for 'cairocffi'.
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
An error occurred when trying to install cairocffi 0.8.0. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'cairocffi'.
Error: Couldn't install: cairocffi 0.8.0
```

**Comment by rockfruit** [comment]
There's a dependency missing on your system, or more than one.  Try this:

sudo apt-get install libffi-dev

I'll update the senaite documentation to include the full list of deps now.

**Comment by phillip-toone** [comment]
Great. Thank you. At the end of the buildout I do the following
```
cat adminPassword.txt
```
to get my admin password and everything looks fine.  But I am unsure about how to start the stand-alone Zope/Plone installation or ZEO cluster.  In that past I have used the following to start bika
```
sudo -u plone_daemon bin/zinstance start
sudo -u plone_daemon bin/client1 fg
```
but I see that this is not an option here. So I try this
```
sudo -u plone_daemon bin/instance start
sudo -u plone_daemon bin/plonectl start
sudo -u plone_daemon bin/plonectl fg
```
and get the following error
```
instance: 2018-03-15 13:36:44 INFO ZServer HTTP server started at Thu Mar 15 13:36:44 2018
	Hostname: 0.0.0.0
	Port: 8080
2018-03-15 13:36:46 WARNING ZODB.blob (17878) Blob dir /usr/local/Plone/zinstance/var/blobstorage/ has insecure mode setting
Traceback (most recent call last):
  File "/usr/local/Plone/zinstance/parts/instance/bin/interpreter", line 306, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
------------------------------ lots of stuff left out here ------------------------------
  File "/usr/local/Plone/buildout-cache/eggs/cffi-1.11.5-py2.7-linux-x86_64.egg/cffi/api.py", line 797, in _load_backend_lib
    raise OSError(msg)
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/usr/local/Plone/zinstance/parts/instance/etc/site.zcml", line 12.2-12.39
    ZopeXMLConfigurationError: File "/usr/local/Plone/buildout-cache/eggs/Products.CMFPlone-4.3.15-py2.7.egg/Products/CMFPlone/meta.zcml", line 42.4-46.10
    OSError: cannot load library 'pango-1.0': pango-1.0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0'
```

**Comment by rockfruit** [comment]
More missing deps ... The full list should be the same as those at
https://github.com/bikalims/bika.lims/wiki/Bika-LIMS-Installation

**Comment by phillip-toone** [comment]
That seems to have fixed all of my issues and the system seems to be installed and functioning correctly. Thank you very much and sorry not catching this on my own.  But I am still a bit unclear about starting the stand-alone Zope/Plone installation or ZEO cluster.  Do I need this
```
sudo -u plone_daemon bin/instance start
```
or this
```
sudo -u plone_daemon bin/plonectl start
```
I did both and it seems to work.

**Comment by rockfruit** [comment]
Hi, I don't know if my previous mail succeeded (sent from phone).  The
error above is another missing dependency, the full list can be cribbed
from the bika.lims installation guide at
https://github.com/bikalims/bika.lims/wiki/Bika-LIMS-Installation

​The starting of the server should be the same in all Plone versions,
whether you're using bika or senaite or niether.

If you installed Plone while logged in as the root user, then you need to
play the plone_group/plone_daemon/plone_buildout dance:

sudo -u plone_buildout bin/buildout
then
sudo -u plone_daemon bin/zeoserver start
sudo -u plone_daemon bin/client1 [start | fg].
or
sudo -u plone_daemon bin/plonect start

bin/plonectl is a script which combines these two commands, and also starts
all additional clients (usually buildout.cfg comes preconfigured with
instances named 'client1' and 'client2').

However if you installed Plone using a normal user account, then you should
be able to simply use

bin/buildout
then
bin/zeoserver start
​bin/client1 [start | fg]
or
bin/plonectl start

without any user/group games.

**Comment by rockfruit** [comment]
The starting of the server should be the same in all Plone versions, whether you're using bika or senaite or niether.

If you installed Plone while logged in as the root user, then you need to play the plone_group/plone_daemon/plone_buildout dance:

`sudo -u plone_buildout bin/buildout`
then
`sudo -u plone_daemon bin/zeoserver start`
`sudo -u plone_daemon bin/client1 [start | fg]`
or
`sudo -u plone_daemon bin/plonect start`

bin/plonectl is a script which combines these two commands, and also starts all additional clients (usually buildout.cfg comes preconfigured with instances named 'client1' and 'client2').

However if you installed Plone using a normal user account, then you should be able to simply use

`bin/buildout`
then
`bin/zeoserver start`
​`bin/client1 [start | fg]`
or
`bin/plonectl start`

without any user/group games.

**Comment by rockfruit** [comment]
Ah and I should add, as you've mentioned 'bin/instance' above:   If you
install Plone using the 'standalone' method, then "bin/instance start" is
all that is required - there should be no zeoserver executable file
present.  If you install using the 'zeo' method, then both bin/zeoserver
and bin/[instance] or bin/[clientX] should exist, and should be started
separately.

For most purposes, it's always recommended to use the "zeo" method.
