### ISSUE TITLE
Sticker label and preview button is not working

### ISSUE THREAD

**Issue by leonardorojass** [senaite/senaite.core#754]
## Steps to reproduce
Click the sticker button (large, small or preview).

![screen shot 2018-04-02 at 13 17 45](https://user-images.githubusercontent.com/2072052/38194588-af591fc6-3678-11e8-910d-78f186acea3a.png)

## Current behavior
When clicking the sticker button (large, small or preview) the system does nothing. The problem persists in all AR states.

## Expected behavior
The sticker should be printed or the preview should be shown.

**Comment by ramonski** [comment]
Hi @leonardorojass, thanks for reporting.
Did you check if your Browser is blocking the popup?
Usually this is shown as a notification in the location bar of the Browser.

**Comment by leonardorojass** [comment]
Yes, there is no popup blocking. For example, when the preview button is clicked the same AR form view is reloaded, instead of the preview page. The same happens with the other buttons (large-small sticker).

**Comment by ramonski** [comment]
Should be fixed in https://github.com/senaite/senaite.core/pull/1239
