### ISSUE TITLE
Analyst name is no longer shown after submitting AR to verification

### ISSUE THREAD

**Issue by leonardorojass** [senaite/senaite.core#755]
## Steps to reproduce
After an AR is submitted for verification the Analyst name is no longer shown in the AR form.

## Current behavior
After an AR is submitted for verification the Analyst name is no longer shown in the AR form. The problems persists in the verified status 

## Expected behavior
The Analyst name should be listed the in the AR form.

## Screenshot (optional)
**Before submitting for verification.**
![screen shot 2018-04-02 at 13 38 30](https://user-images.githubusercontent.com/2072052/38195130-2b3c18e8-367c-11e8-869f-dc22bd42b214.png)

**After submitting for verification.**
![screen shot 2018-04-02 at 13 39 04](https://user-images.githubusercontent.com/2072052/38195133-2f206f36-367c-11e8-9fcd-439a7e8766ae.png)

**Comment by xispa** [comment]
Cannot reproduce when using `senaite.core v1.2.4`

![analyses1](https://user-images.githubusercontent.com/832627/38772810-97ec4fae-403f-11e8-9b6d-4413d04653e1.png)

![analyses2](https://user-images.githubusercontent.com/832627/38772812-9b86fee8-403f-11e8-8c33-c8988d0cc1f1.png)
