### ISSUE TITLE
Error when creating a new Sampling Round

### ISSUE THREAD

**Issue by leonardorojass** [senaite/senaite.core#757]
## Steps to reproduce
Create a new Sampling Round for any given client with a Sampling Round Template.

## Current behavior
The first step to create a sampling round is working fine. The problem is in the second step during the AR form creation, as it does not call the template values and does not permit to selected them.

## Expected behavior
The AR form should pull the Sampling Round Template information automatically, and also should permit to change the values manually.

## Screenshot (optional)
![screen shot 2018-04-02 at 14 53 16](https://user-images.githubusercontent.com/2072052/38197097-e1aca1c4-3686-11e8-9b44-f637388c79e9.png)

**Comment by leonardorojass** [comment]
This issue persists in the latest version.

**Comment by ramonski** [comment]
Sampling rounds will be no longer part of senaite.core 1.3.3: https://github.com/senaite/senaite.core/pull/1531
