### ISSUE TITLE
Program will not allow "Statement/invoices"

### ISSUE THREAD

**Issue by Caloaks** [senaite/senaite.core#766]
I created a Senaite websites hosted on AWS.  From the home page if I click "Statements" It provides me with the error below.  Initially I had the senaite.health installed and was told it is possible that the senaite.lims and senaite.health are not working well and creating a "template issue".  I have removed senaite.health and the same error occurs.  I have also changed the theme with no resolution. 

 I appreciate your assistance.

**The fourth picture (health + Lims) was the error prior to removing senaite.health. 

![shot 1](https://user-images.githubusercontent.com/27759850/38538722-f0f893fe-3c49-11e8-8567-951f468435fa.png)
![shot 2](https://user-images.githubusercontent.com/27759850/38538723-f112f456-3c49-11e8-8426-92f91648eecb.png)
![shot 2 text](https://user-images.githubusercontent.com/27759850/38538724-f12d0508-3c49-11e8-8c1f-09b1c110099c.png)
![health lims](https://user-images.githubusercontent.com/27759850/38538902-a5afe4e6-3c4a-11e8-8318-37749aaa60d1.png)

**Comment by juangallostra** [comment]
@Caloaks which version of `senaite.core` are you using? This should be fixed as per #743 which was included in version 1.2.4 and released 3 days ago. 

Just in case, to check your current version you should go to Site Setup -> Zope Management Interface -> Portal setup -> Upgrades tab and then choose `bika.lims:default` profile

**Comment by xispa** [comment]
Closed as per https://github.com/senaite/senaite.core/pull/743
