### ISSUE TITLE
Search Filter box not working properly for ARs

### ISSUE THREAD

**Issue by min2great** [senaite/senaite.core#773]
The Filter-box on the listing of Analysis Request does not work correctly (or at least normally). For example, if I want to search 'blood-0123-R01' and I type 'blood-01' or 'blood-012', the AR will not appear in the result. It will appear only when I type 'blood-0123' in filter box.

Senaite LIMS 1.2.0

**Comment by ramonski** [comment]
Dear Khurram, could you please provide the version of senaite.core you are using? Please note, the latest version is 1.2.4 https://pypi.org/project/senaite.core/1.2.4/

**Comment by xispa** [comment]
Closed as per https://github.com/senaite/senaite.core/pull/619 and https://github.com/senaite/senaite.core/pull/771
