### ISSUE TITLE
Lab Clerks cannot see Client Contacts

### ISSUE THREAD

**Issue by nihadness** [senaite/senaite.core#787]
## Steps to reproduce
1. Log in as `LabManager` and add a new Contact to any Client.
2. Log out and log in as a Lab Clerk.
3. Go to the Client view and try to find that 'Client Contact'. 

## Current behavior
'Contacts' tab is missing for Lab Clerks. On some instances, lab clerks cannot even choose Client Contact when creating AR's which is blocker. 
 
## Expected behavior
Lab Clerks can see 'Contacts' tab and all Client Contacts.

**Comment by ramonski** [comment]
This is just a view issue, see here:
https://github.com/senaite/senaite.core/blob/master/bika/lims/profiles/default/types/Client.xml#L213

Going directly on the /contacts view should display the contacts.

**Comment by ramonski** [comment]
I noticed that on several places that the permissions for views, actions etc. are not in sync with the actual object permissions 😟

**Comment by nihadness** [comment]
yeaps, view part is easy to solve, need to add 'LabClerk' to [Modify permission here](https://github.com/senaite/senaite.core/blob/master/bika/lims/permissions.py#L330) and [after modification here](https://github.com/senaite/senaite.core/blob/master/bika/lims/subscribers/objectmodified.py#L39) ...

**Comment by nihadness** [comment]
I just thought it was the same reason but now I see that it could happen because of Sync... The thing is that when checking from ZMI, I see that for specific contact, 'LabClerk' role has enough permissions to view/modify the contact, but it doesn't appear in the list while going to '/contacts' page. No idea why it happens so far :(

**Comment by ramonski** [comment]
Hi @nihadness, I just found this setup config:

<img width="1152" alt="setup senaite 2018-04-25 22-37-55" src="https://user-images.githubusercontent.com/713193/39271466-70485d92-48d9-11e8-8931-5f97e4783cb5.png">

I think that is bound to "BIKA: Edit Clients", which should be also the permission set on the tab here:
https://github.com/senaite/senaite.core/blob/master/bika/lims/profiles/default/types/Client.xml#L213

**Comment by xispa** [comment]
Pheeew, nice catch!

**Comment by nihadness** [comment]
Really a good one! :)
Then I think we can close https://github.com/senaite/senaite.core/pull/788 and move on?
By the way @ramonski , I also found out that the problem I was facing was totally different than a permission issue on the Synchronized instance I was working with. But I would like to know where you faced permission bugs that happens because of the Sync, since we are planning to migrate a few instances soon.

**Comment by ramonski** [comment]
Not sure if we can close this one, because the permission for the Tab visibility is set to "Modify portal content", but should be IMO "BIKA: Edit Clients".

@nihadness  can you please check if this tab is visible for Lab Clerks if the Setup option is set?

Regarding `senaite.sync`, I actually didn't migrate any sites with it until now...

**Comment by nihadness** [comment]
yes @ramonski "Bika Setup" handles it correctly. When they have 'Edit Clients' enabled, they see that tab. So, maybe Tab visibility permission should be 'View' ? If you view the Client info, you should be able to see Contacts as well, right? 

and forget about `senaite.sync` I misunderstood your previous comment.

**Comment by ramonski** [comment]
I think this on can be closed...
