### ISSUE TITLE
Remove "AdHoc" Field from AR/Sample

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.core#793]
## Description

This field is almost never needed and has no further functionality except that it is there and can be switched on/off...

## Todo

- [ ] Remove AdHoc Field from AR and Samples

**Comment by ramonski** [comment]
This will be handled by a "label" in the future.

**Comment by xispa** [comment]
https://github.com/senaite/senaite.core/pull/1180/files#diff-9d57b6da936ef609e76f1d66d7886474L1231
