### ISSUE TITLE
AR Listing inline edit for Date Sampled not working when Sampler is captured during AR create

### ISSUE THREAD

**Issue by Lunga001** [senaite/senaite.core#799]
## Steps to reproduce

1. Go to Bika Setup under Sampling and COC tab and tick Enable Sampling if it's not ticked.
2. Add 4 ARs and give the field Sampler a value, enter all the required fields and save
3. You should be redirected to AR Listing, and on that listing Date Sampled column should be editable, change the Date Sampled and Click Sample transition at the bottom

![happy hills senaite](https://user-images.githubusercontent.com/10023210/39291760-5964c15a-4934-11e8-9bb5-3964e2661cc2.png)

## Current behavior

Sampling Date does not get saved, a "No changes made" message is displayed

## Expected behavior

Should changed Date Sampled to the new updated Date.

## Screenshot (optional)

Also note that when both Sampler field and Date Sampled field are not are both empty(not captured during AR add) then the inline-edit works.

**Comment by juangallostra** [comment]
Closing as per #805
