### ISSUE TITLE
AutoLogoff and PasswordLifetime in Setup have no functionality

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.core#845]
## Description

The LIMS Setup provides the options

- Password lifetime
- Automatic log-off

These fields have no functionality and should be removed

## Current behavior

The fields are not linked to any logic that provides the expected behavior

## Expected behavior

The functionality is given or the fields are not there.

## Screenshot (optional)

<img width="1015" alt="setup senaite 2018-05-29 22-59-15" src="https://user-images.githubusercontent.com/713193/40685304-29bd7328-6394-11e8-89f9-40083661a567.png">

**Comment by lemoene** [comment]
Quite important functionality. @rockfruit you had it going last after that JH Jones person's post? Cannot see anything immediate re Plone (really?) in this regard - was it our own cookie manipulation or JS?

**Comment by ramonski** [comment]
This functionality might depend on [plone.session](https://github.com/plone/plone.session). However,  I don't find any hints for this in the code so far...
