### ISSUE TITLE
"Insufficient Privileges" error when trying to open ARImport record in View/Edit mode using client role

### ISSUE THREAD

**Issue by pioneerpathan** [senaite/senaite.core#847]
## Steps to reproduce

1. Go to ZMI >senaite > clients > Security tab > Tick the "BIKA: Manage ARImport" permission for **Client** role. So now you made **AR Import** functionality available to users with **Client** role.
2. Now login with a user having role as a **Client**.
3. Go inside client's tabs. Click on **Imports** tab as shown below and click on **AR Import** button to upload a .csv file. 

![image](https://user-images.githubusercontent.com/9590337/40972697-2cc892b4-68df-11e8-990e-baf601009b5b.png)

4. Upon file upload, system will read the data from csv file  and do an invalid to valid transition. Once it is validated, system will redirect to **View/Edit** mode of AR Import to do further processing.
5. There you will come across **Insufficient Privileges** error because you are logged in with **Client** role. The URL at that time appears like **http://10.10.0.1:8080/senaite/acl_users/credentials_cookie_auth/require_login?came_from=http://10.10.0.1:8080/senaite/clients/client-2/AI-007/view**

![image](https://user-images.githubusercontent.com/9590337/40973024-53bb8cae-68e0-11e8-9d52-324a473576dc.png)

In error log it reports, Request URL as **http://10.10.0.1:8080/senaite/clients/client-2/AI-007/base_view**
and Exception value as -

**You are not allowed to access 'Title' in this context - Expression: " python: (value and hasattr(value, 'Title')) and value.Title() or '" - Filename: ... ore/bika/lims/skins/bika/bika_widgets/referencewidget.pt - Location: (line 24: col 33) - Source: ... python: (value and hasattr(value, 'Title')) and value.Title() or '' ... ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ - Expression: "field/multiValued" - Filename: ... ore/bika/lims/skins/bika/bika_widgets/referencewidget.pt - Location: (line 15: col 43) - Source: ... alued tal:condition="not:field/multiValued"> ^^^^^^^^^^^^^^^^^ - Expression: "widget_view" - Filename: ... gg/Products/Archetypes/skins/archetypes/widgets/field.pt - Location: (line 53: col 30) - Source: <metal:block use-macro="widget_view" /> ^^^^^^^^^^^ - Expression: "data_macro|default" - Filename: ... gg/Products/Archetypes/skins/archetypes/widgets/field.pt - Location: (line 28: col 37) - Source: ... tal:use_data use-macro="data_macro|default" /> ^^^^^^^^^^^^^^^^^^ - Expression: "context/widgets/field/macros/base_view" - Filename: ... gg/Products/Archetypes/skins/archetypes/widgets/field.pt - Location: (line 61: col 42) - Source: ... ew use-macro="context/widgets/field/macros/base_view" /> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ - Expression: "field_macro" - Filename: ... 2-py2.7.egg/Products/Archetypes/skins/archetypes/base.pt - Location: (line 25: col 42) - Source: <metal:use_field use-macro="field_macro" /> ^^^^^^^^^^^ - Expression: "body_macro" - Filename: ... .7.egg/Products/Archetypes/skins/archetypes/base_view.pt - Location: (line 81: col 35) - Source: <metal:use_body use-macro="body_macro" /> ^^^^^^^^^^ - Expression: "provider:plone.abovecontentbody" - Filename: ... theme/sunburst/skins/sunburst_templates/main_template.pt - Location: (line 115: col 89) - Source: ... ent="structure provider:plone.abovecontentbody" tal:conditio ... ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ - Expression: "provider:plone.abovecontent" - Filename: ... theme/sunburst/skins/sunburst_templates/main_template.pt - Location: (line 69: col 67) - Source: ... ntent="structure provider:plone.abovecontent" tal:condition= ... ^^^^^^^^^^^^^^^^^^^^^^^^^^^ - Expression: "context/main_template/macros/master" - Filename: ... .7.egg/Products/Archetypes/skins/archetypes/base_view.pt - Location: (line 7: col 23) - Source: ... etal:use-macro="context/main_template/macros/master" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ - Arguments: repeat: {...} (0) template: <ImplicitAcquisitionWrapper base_view at 0x7f76fad19320> modules: <instance - at 0x7f77175bc7a0> here: <ImplicitAcquisitionWrapper AI-030 at 0x7f76fad19c80> user: <ImplicitAcquisitionWrapper - at 0x7f76f88dffa0> nothing: <NoneType - at 0x7a8030> target_language: <NoneType - at 0x7a8030> container: <ImplicitAcquisitionWrapper AI-030 at 0x7f76fad19c80> default: <object - at 0x7f7724112be0> root: <ImplicitAcquisitionWrapper Zope at 0x7f76fa703b90> request: <instance - at 0x7f76f88d3e18> wrapped_repeat: <SafeMapping - at 0x7f76f7bacfc8> traverse_subpath: <list - at 0x7f76f85c0998> loop: {...} (5) context: <ImplicitAcquisitionWrapper AI-030 at 0x7f76fad19c80> translate: <function translate at 0x7f76f774e5f0> macroname: master options: {...} (1)**

6. Now when you come to **Imports** tab again, it will list down the import entry which you just tried with **Pending** status. And again you try to open it in **Edit** mode to import, it would give same error.
7. I have tried same functionality with LabManager login which works perfectly. 

## Current behavior

1. Though **BIKA: Manage ARImport** permission has been assigned to **client** role, it would not allow user with client role to **view/edit** records in import tab.

## Expected behavior

1. I think it is matter of permission handling. The functionality should work same for **Client** as it is working for **LabManager**. 
2. It should allow to open import entry in **View/Edit** mode, so that records in **Pending** state can be marked to **Imported** which is the purpose of **AR Import** functionality.

**Comment by Lunga001** [comment]
@pioneerpathan please try add `mp(ManageARImport,` ['Manager', 'LabManager', 'LabClerk', 'Owner', 'Client'], 0)` below line https://github.com/senaite/senaite.core/blob/master/bika/lims/permissions.py#L320

**Comment by uqmtobe** [comment]
Hi guys, can anyone assist with the correct .csv template for ARImport.  My header info imports ok plus the analysis tables, but my dates/matrix/sample type 
![Import Template Gaps](https://user-images.githubusercontent.com/16073814/72700108-976f2c00-3b96-11ea-8670-de03e0841cdd.png)
are ignored on import.  any advice appreciated.

**Comment by pioneerpathan** [comment]
Hi @uqmtobe. 
You should mentioned 'Sample Type Prefix' of a sample type while preparing ARImport .csv file. For date, try to follow 'YYYY-MM-DD' date format. Please keep in mind the 'CASE-SENSETIVITY' while using import option. Check case sensitivity for sample matrix. Hope this will help you.

**Comment by mikejmets** [comment]
SampleType is required

**Comment by ramonski** [comment]
ARImport is no longer part of `senaite.core` 1.3.3: https://github.com/senaite/senaite.core/pull/1530
