### ISSUE TITLE
Cannot view/edit Supplier. Reference Samples displayed as default

### ISSUE THREAD

**Issue by Migulo** [senaite/senaite.core#860]
## Steps to reproduce
Try to open/view specific supplier in "suppliers" section
## Current behavior
"Reference sample" will be opened instead
## Expected behavior
Specific supplier should be opened for viewing/editing

**Comment by xispa** [comment]
Basically, once the Supplier is created, there is no "View"/"Edit" tab available and since the user is redirected to "Reference Samples", there is no way to see or edit the Supplier actually

**Comment by Migulo** [comment]
The bug reappeared in the current senaite version
