### ISSUE TITLE
plone_daemon user does not have enough permissions for eggs folder

### ISSUE THREAD

**Issue by Migulo** [senaite/senaite.core#861]
## Steps to reproduce
buildout -n (sudo)
## Current behavior
After performing a "buildout -n" the plone_daemon user does have insufficient permissions to enter /usr/local/Plone/buildout_cache/eggs.

--> The permissions have to be changed manually
## Expected behavior
The proper permissions should be set automatically (like it´s been the case in "older" versions of Senaite and/or Bika)

**Comment by ramonski** [comment]
Thanks for reporting @Migulo.

I guess you used the Unified Installer to install Plone?

If so, then this installer usually also installs a Python version in a folder next to the buildout folder called `python2.7`. The generated  scripts in the buildout `bin` folder, e.g. `bin/buildout` and `bin/client...` scripts use exactly this specific Python installation.

```bash
senaite@ridingbytes:~/senaitelims$ head bin/buildout

#!/home/senaite/senaitelims/../python2.7/bin/python

import sys
sys.path[0:0] = [
  '/home/senaite/buildout-cache/eggs/zc.buildout-2.11.2-py2.7.egg',
  '/home/senaite/python2.7/lib/python2.7/site-packages',
  ]

import zc.buildout.buildout
```

```bash
senaite@ridingbytes:~/senaitelims$ head bin/client1
#!/home/senaite/senaitelims/../python2.7/bin/python

import sys
sys.path[0:0] = [
  '/home/senaite/buildout-cache/eggs/Plone-4.3.15-py2.7.egg',
  '/home/senaite/buildout-cache/eggs/Pillow-3.3.0-py2.7-linux-x86_64.egg',
  '/home/senaite/senaitelims/src/senaite.core',
  '/home/senaite/senaitelims/src/senaite.lims/src',
  '/home/senaite/senaitelims/src/senaite.impress/src',
  '/home/senaite/senaitelims/src/senaite.jsonapi/src',
```

However, this does **not** change your default Python path on your machine:

```bash
senaite@ridingbytes:~senaitelims$ which python
/usr/bin/python
```

Hence, when you do `python bootstrap.py` in your buildout directory, you end up with the following scripts:

```bash
senaite@ridingbytes:~/senaitelims$ head bin/buildout

#!/usr/bin/python
...
```

```bash
senaite@ridingbytes:~/senaitelims$ head bin/client1

#!/usr/bin/python
...
```

While this seems to work when you still have a Python 2.x interpreter on your machine:

```
senaite@ridingbytes:~/$ python --version
Python 2.7.12
```

It will installs newly downloaded eggs with `root` privileges and you get the issue you described.

Please let me know if this is the case on your machine.

Thanks, Ramon

**Comment by ramonski** [comment]
Ok, I found now this solution for a common buildout setup. Add this in `live.cfg`:

```
[setpermissions]
recipe = plone.recipe.command
command =
    # Dummy references to force this to execute after referenced parts
    echo ${backup:location} > /dev/null
    chmod 600 .installed.cfg
    # Make sure anything we've created in var is r/w by our group, but no-one else
    chmod -R ug+rwX,o-rwx ${buildout:var-dir}
    chmod -R ug+rwX,o-rwx ${buildout:backups-dir}
    chmod 754 ${buildout:directory}/bin/*
    # ---------------------------------------------------------
    # Fix for https://github.com/senaite/senaite.core/issues/861
    # Make all eggs are r/w by our group
    chmod -R ug+rwX,o-rwx ${buildout:eggs-directory}
    # ---------------------------------------------------------
update-command = ${:command}
```

However, this buildout config ships with the unified installer, therefore we can not provide this setting per default, but we could at least document it somewhere.

Seems to me like `zopyx.txng3.core-3.6.2-py2.7.egg` was improperly distributed...

**Comment by ramonski** [comment]
Also see here: https://github.com/senaite/senaite.ansible-playbook#permission-denied

**Comment by ramonski** [comment]
I would say that when we have this documented in the installation instructions, we can close this issue.
