### ISSUE TITLE
AR status does not change to "to be verified" after being retracted

### ISSUE THREAD

**Issue by Migulo** [senaite/senaite.core#862]
## Steps to reproduce
1. Do one AR, enter the sample results, save --> AR status changes to "to be verified"
2. Retract the results, reenter new results, save --> 
## Current behavior
Every single result shows "to be verified", but overall AR status does no longer change to "to be verified", but sticks with " sample preparation"

## Expected behavior
AR status should change to "to be verified"

**Comment by xispa** [comment]
I feel this happens only when you have the Sample preparation workflow enabled and the Sample (or AR) was previously transitioned from "Received" to "in preparation". Excerpt from gitter about a similar issue:
> **Q**: I experienced some strange behaviour regarding "Analysis request": Sometimes the status of the AR seems to change back to a former status (i.e. from "Received" to "Sample due". Up to know, it´s not reproducable, but I get the following error messages in the bika console:
> WARNING: Bika guard_sample_prep_complete_transition: WorkflowException No workflow provides '{name}' information.
> **A**: `sample_prep_complete` transition takes place when "moving" a Sample from "in preparation" to a "received" state. To ensure that transition is possible, the guard guard_sample_prep_complete_transition is checked [here](https://github.com/senaite/senaite.core/blob/master/bika/lims/workflow/sample/guards.py#L41-L69). This guard relies on the state variable `sampleprep_review_state`, that in turn, is only applicable when `workflow sampleprep_simple` is used. Unfortunately, seems that this `sampleprep_simple` workflow is not assigned by default to neither [Sample](https://github.com/senaite/senaite.core/blob/999a5eec62562da8c10f9fc15822a40806b198a6/bika/lims/profiles/default/workflows.xml#L418-L425) nor [AnalysisRequest](https://github.com/senaite/senaite.core/blob/999a5eec62562da8c10f9fc15822a40806b198a6/bika/lims/profiles/default/workflows.xml#L90-L97) objects. Thus, that transition "in preparation" to "received" state will never be possible and since there is a try..except in that guard, a warning will always appear instead of a big Traceback. [...]. Since these guards are automatically called by Plone's DCWorkflow depending on the current status of the object, could be the transition "sample_prep_complete" being defined somewhere else. In that case, you will get that warning even if your Sample is not in sample_prep state.

**Comment by xispa** [comment]
Related with https://github.com/senaite/senaite.core/issues/862, because "sample preparation" state is involved

**Comment by rockfruit** [comment]
With current versions of all packages, it appears to me that this code (the sample preparation story) is not functioning at all.  @Migulo I'm curious, are you attempting to make use of these custom workflows?

Considering that it's causing issues on github, almost certainly not being used, and has no tests at all, I'm in favor of removing this code from senaite.core.

If it's useful to anyone, I still think it should be refactored out into it's own package.

Thoughts?  @ramonski @xispa

**Comment by xispa** [comment]
I myself don't know anyone using this small workflow. If I remember correctly, this workflow was used to allow the binding of custom preservation workflows, but I am not sure. I suggest to remove the preparation workflow and if we feel it is necessary later, redo it in a new add-on
