### ISSUE TITLE
Secondary AR changes received date of sample

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#863]
## Steps to reproduce
Create secondary AR of an existing sample.

## Current behavior
Date received of AR and **sample** is updated with the current date.

## Expected behavior
Date received relates to the sample and must not change.
(It is not Date created, which relates to the new AR.)

## Screenshot (optional)
![grafik](https://user-images.githubusercontent.com/25460329/41821819-682f9904-77e6-11e8-9af5-16e9a2115695.png)

**Comment by xispa** [comment]
This column (from Analysis Requests list) refers to the date when the Analysis Request was received. Notice the "Date received" for the first AR (H2O-0003-R01) is kept, while the "Date received" for the secondary AR matches with the date this secondary AR was received. The transition from `sample_due` to `received` is performed automatically because is a secondary AR. Therefore, this "Date received" matches with the "Date created".

If you visit the Samples list, you will see that the "Date received" for sample H20-0003 has not changed.

Thus, I think this is the correct behavior.

**Comment by grulisco** [comment]
This behavior is highly confusing, because from the users view "Date received" normally corresponds with receiving the **sample** belonging to the AR. After creating an AR this date is empty:
![screenshot_20180625_224936](https://user-images.githubusercontent.com/25460329/41875063-0a77755e-78ca-11e8-9f10-0f06da596ca6.png)

If this attribute should really belong to the AR, it should work the same way, whether on primary or secondary ARs. But identical dates for creation and reception of the AR would be of no sense at all.

"Date received" of the **sample** should be the right choice and must not change with additional ARs.
In contrast to your statement, in my example at senaite demo it **did** change from 23 to 24 after creating 2nd AR:
![screenshot_20180625_230430](https://user-images.githubusercontent.com/25460329/41875743-1f47bb22-78cc-11e8-9fbd-018f77a378f3.png)

Speaking with ISO 17025, the date of reception of the **sample** has to be named in the analytical report.
This is currently not the case in senaite for this situation.

@xispa Please consider to reopen this issue

**Comment by grulisco** [comment]
In addition the Log of H2O-0003, where the old "Date Received" is kept:
![grafik](https://user-images.githubusercontent.com/25460329/41876556-75ebe3fc-78ce-11e8-90f6-b17397692786.png)

Two opposite attributes...

**Comment by xispa** [comment]
Thanks @grulisco for your hands up!. Agree, we need to make AR's "Date Received" to always be the date when the "Sample" was received. The strange thing here is that in my instance, the Sample date did not change after creating the secondary AR. Will check again. Reopening!

**Comment by grulisco** [comment]
@xispa Thanks for reopening :smile: 
I observed this issue first in our own instance and in the demo at senaite.ridingbytes.com.

**Comment by grulisco** [comment]
@xispa @rockfruit : @ramonski just updated our testmachine for me containing PR #899 to check the state of this issue here.
Date Received seems to be a property of sample now as intended.
But creating a secondary AR **still** sets Date Received to the current datetime, although we wanted to keep it untouched.
At least it is editable in the early stages, but if the primary AR was verified, the date is set definitely wrong.

**Comment by xispa** [comment]
Thanks @grulisco , removing issue-done label and placing a bunch of red colors to address this one asap

**Comment by grulisco** [comment]
This wrong behaviour happens when creating a secondary AR by sample view or referencing existing sample in AR Add.
While **invalidating** an AR which creates a secondary AR automatically Date Received does not change, which is correct.

**Comment by grulisco** [comment]
Re colors: the more badges the more glory :smiley:
