### ISSUE TITLE
DateTimeField failed to format date string ' ' with 'date_format_short'

### ISSUE THREAD

**Issue by Migulo** [senaite/senaite.core#866]
## Steps to reproduce
- Change the status of an AR 
- Localisation set to "German"
## Current behavior
Error message within the server console:
DateTimeField failed to format date string ' ' with 'date_format_short'

Ramonski´s feedback on this topic (@gitter):

The (first) message in the console is related to a failed attempt to format the date string into the localized version, e.g. MM.dd.YYYY. It is indeed a bug...

## Expected behavior
Correct date format in localized version

**Comment by xispa** [comment]
@ramonski , @Migulo is this one still an issue?

**Comment by ramonski** [comment]
Fixed in https://github.com/senaite/senaite.core/pull/1693
