### ISSUE TITLE
 Bika guard_sample_prep_complete_transition

### ISSUE THREAD

**Issue by Migulo** [senaite/senaite.core#867]
## Steps to reproduce
•Change the status of a sample within AR from "sample due" to "received" (not through workflow)
## Current behavior
Undefined status, sometime the status changes back to "sample due" by its own

Error message within the console:

_Bika guard_sample_prep_complete_transition: WorkflowException No workflow provides '{name}' information._

**Xispa´s feedback on this topic (@gitter):**
sample_prep_completetransition takes place when "moving" a Sample from "in preparation" to a "received" state. To ensure that transition is possible, the guard guard_sample_prep_complete_transition is checked here. This guard relies on the state variable sampleprep_review_state, that in turn, is only applicable when workflow sampleprep_simpleis used. Unfortunately, seems that this sampleprep_simpleworkflow is not assigned by default to neither Sample nor AnalysisRequest objects. Thus, that transition "in preparation" to "received" state will never be possible and since there is a try..except in that guard, a warning will always appear instead of a big Traceback. So please, report this issue at https://github.com/senaite/senaite.core/issues/new (and paste this argumentation, if you don't mind). Since these guards are automatically called by Plone's DCWorkflow depending on the current status of the object, could be the transition "sample_prep_complete" being defined somewhere else. In that case, you will get that warning even if your Sample is not in sample_prep state.

## Expected behavior
Change the status of a sample from within AR (without predefined workflow)

**Comment by rockfruit** [comment]
@Migulo hi, I have been unable to reproduce this issue.  In this issue or in the gitter channel, when you have some time, I'd like to have a conversation about this. Please ping me when you're available!

**Comment by rockfruit** [comment]
@xispa 09:42
I remember that there was a kind of hack so you could "bind" your own preparation workflow to the core's workflow, but I don't know of anyone using it

@rockfruit 09:43
for now though, I just want it to not cause errors for unsuspecting users who are not using it....

@xispa 09:44
Please, remove that preparation workflow and if later is necessary, we'll create an specific add-on for it

@rockfruit 09:44
done.
