### ISSUE TITLE
Order of Interim Fields not maintained on ARs. Rebuilding Dry Matter results

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#888]
Also see https://community.senaite.org/t/order-of-interim-fields-on-wss-and-ar-results-tabs/41/6

https://github.com/senaite/senaite.core/issues/483

## Steps to reproduce

Have not tested on the RB demo, but seen on two instances now. Maybe I am missing something

Trying to build up the Dry Matter Calculation,  all new Calcs and ASs, I don't get the Interim Field order to be rendered correctly on AR Manage results tab _Edit, and WSs too_

![image](https://user-images.githubusercontent.com/1196034/42230736-05033dc6-7eea-11e8-9990-73fa402b5928.png)

![image](https://user-images.githubusercontent.com/1196034/42230801-2e35e428-7eea-11e8-8400-4b5078d7d7eb.png)

The AS using the formula copies the Interim Field order correctly, but loses the default values already

![image](https://user-images.githubusercontent.com/1196034/42231173-1f5958c6-7eeb-11e8-8b8c-d9de97cf50e2.png)

## Current behavior

On the AR using the new AS the Interim field order is not maintained

![image](https://user-images.githubusercontent.com/1196034/42231265-63d67920-7eeb-11e8-840c-f5c9dd7d9e2b.png)

Worksheets

![image](https://user-images.githubusercontent.com/1196034/42233383-af231f90-7ef1-11e8-9fb7-f20c378a56e5.png)

The moisture calc is a dependent thus of the eventual DM calculation, in this case calculating _As Is_ results form analyses on the dried material

## Expected behavior

The Interim fields on the AR in the same order as on the AS

![image](https://user-images.githubusercontent.com/1196034/42231388-b4fd3a8c-7eeb-11e8-80e6-d09194027ddc.png)

and eventually the _As Is_ DM calc

It is not critical which Calc's fields are displayed first left to right (the dependencies first if easily possible

![image](https://user-images.githubusercontent.com/1196034/42232634-5be1a5b0-7eef-11e8-9c16-1d7250e5b58c.png)

**Comment by ramonski** [comment]
Works for `senaite.core` >= 1.2.6, except that it is reversed in the results capturing, which might be acceptable.

<img width="1908" alt="dry matter senaite 2018-07-03 21-13-01" src="https://user-images.githubusercontent.com/713193/42239943-e66fb828-7f05-11e8-8b6d-4553f0cf0419.png">


<img width="1891" alt="dry matter senaite 2018-07-03 21-12-29" src="https://user-images.githubusercontent.com/713193/42239926-d5e3b720-7f05-11e8-9623-7951436b8a71.png">

<img width="1900" alt="h2o-0028-r01 senaite 2018-07-03 21-16-14" src="https://user-images.githubusercontent.com/713193/42240081-6891a2b2-7f06-11e8-8725-9197eb5e0735.png">

**Comment by lemoene** [comment]
please also test with the combined (or more) calcs per AR. In requested access at RB demo again

**Comment by lemoene** [comment]
username not found

**Comment by lemoene** [comment]
Cannot immediately see which version, upgraded end last week

**Comment by ramonski** [comment]
Looks perfectly fine to me. Please upgrade to the latest version.

<img width="1899" alt="h2o-0029-r01 senaite 2018-07-03 21-46-58" src="https://user-images.githubusercontent.com/713193/42241410-b801ba04-7f0a-11e8-95da-9577a0e98496.png">

**Comment by lemoene** [comment]
cool. will xcheck versions. workaround is to reverse order them in the config. should do

**Comment by lemoene** [comment]
I found a few issues with the Interims, will log them separately as I retest on fresh Senaite 128 install and setup data 

This one is back, The Interim field order is not maintained from Calc/AS to AR/WS, seems to sort them alphabetically

I created a new Calc and AS. In this use case I did not use a specific Method

![image](https://user-images.githubusercontent.com/1196034/43398536-a83ee200-9408-11e8-8ebe-88ed67b5aef0.png)

![image](https://user-images.githubusercontent.com/1196034/43398567-c2e03d5c-9408-11e8-8d38-2e5e18f4ac41.png)

![image](https://user-images.githubusercontent.com/1196034/43398644-fef9d096-9408-11e8-81f0-7e0c2131606a.png)

WS turns out Interims sorted alphabetically

![image](https://user-images.githubusercontent.com/1196034/43398749-3959e776-9409-11e8-8067-70d14f586583.png)

**Comment by lemoene** [comment]
The trend then continues when more than one Calc is used on the same WS, here in combination with a WS Wide correction factor

![image](https://user-images.githubusercontent.com/1196034/43400154-356f8ffe-940d-11e8-864a-d8722821ec6f.png)

![image](https://user-images.githubusercontent.com/1196034/43400288-a2e4a54c-940d-11e8-8791-5a2ddb8df468.png)

These calcs on different results on the same WS is necessary where primary results are arrived at by calculation, needs to be reported, and then processed further in a secondary part of the method. Also for DM

We'd be home if the Interim fields can be displayed L to R 

- in  the order they are configured on the Calculation (and after renaming etc. on the AS)

- grouped per Analysis, i propose same order L - R as the Analyses top down on the W
