### ISSUE TITLE
Remove `uniquefieldvalidator` for Client Names

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.core#908]
## Steps to reproduce

- Create a client named "Client A" with id "A"
- Create a client named "Client A" with id "B"

## Current behavior

It is not allowed to have the same Client Name more than once

## Expected behavior

The same client name can be assigned more than once.

There is no need that the client name must be unique and is only a side effect coming from the base class: https://github.com/senaite/senaite.core/blob/master/bika/lims/content/organisation.py#L26

**Comment by xispa** [comment]
I cannot think of a reason why two different clients might have the same name. IMO, it could generate confusions and missunderstandings very easily

**Comment by ramonski** [comment]
Happens quite often when you address different divisions in the same company or branches. So you want to have the same company name in the report, but a different address for example.

**Comment by ramonski** [comment]
IMO if it is not required as a primary key, we shouldn't force it to be unique.

**Comment by xispa** [comment]
Good reasoning, thanks!

**Comment by rockfruit** [comment]
This uniqueness requirement was actually once used where submitted form values included Strings instead of UIDs, this is no longer the case though.
