### ISSUE TITLE
Interim Field Default 0, Hide and Apply Wide not copied from Calculation to AS

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#951]
Because of the available workarounds, not critical

_**Edit**_, _Ditto for Hidden, added in title, see new comment_

# Steps to reproduce

Create a Calculation that contains an Interim field default value of 0.0

![image](https://user-images.githubusercontent.com/1196034/43409159-758624de-9423-11e8-8ced-51e6d0fa274d.png)

And another/same with a Correction Factor that is enabled to apply WS wide

![image](https://user-images.githubusercontent.com/1196034/43409225-a799183c-9423-11e8-9a61-e432d47696d6.png)

And create ASs using these Calculations

## Current behavior

All default values are copied form the Calculation, except 0, and not applied unless edited and saved on the AS

![image](https://user-images.githubusercontent.com/1196034/43409399-18cdf6c6-9424-11e8-8f5c-9029a62dab1b.png)

![image](https://user-images.githubusercontent.com/1196034/43409418-268da054-9424-11e8-9c0b-b824f508b4ad.png)

after edits on the AS

![image](https://user-images.githubusercontent.com/1196034/43409506-60fa18da-9424-11e8-8de9-2f0d89a486a0.png)

The 'Apply Wide' setting also does not get copied, neither does it save when manually enabled again on the AS, but seems to work regardless?

![image](https://user-images.githubusercontent.com/1196034/43409598-a9c426a0-9424-11e8-94f4-0ec542c061ec.png)

![image](https://user-images.githubusercontent.com/1196034/43409674-dae02f4a-9424-11e8-82e9-d1fc7ef82b8e.png)

![image](https://user-images.githubusercontent.com/1196034/43409751-0bffeb88-9425-11e8-9edb-3ef800d1681c.png)

## Expected behavior

When a Calculation is used on an AS, all its default configuration to be copied there

**Comment by lemoene** [comment]
Configuring a Hidden Interim field (not sure how this is used) on the Calc, gets duplicated to the AS

![image](https://user-images.githubusercontent.com/1196034/43452760-911390c0-94b8-11e8-8df5-9d31168fd2b2.png)

![image](https://user-images.githubusercontent.com/1196034/43452795-a56ffb12-94b8-11e8-8e3e-ecf0ef03b47c.png)

but does not get saved first time round

![image](https://user-images.githubusercontent.com/1196034/43452892-dad5354c-94b8-11e8-931a-87b666d06a67.png)

When I navigate back to it on the AS' Method tab, and manually set it, it gets saved and applied. Can be worked around thus

![image](https://user-images.githubusercontent.com/1196034/43452982-1b56dbde-94b9-11e8-8792-4e5e07a0ce7d.png)

**Comment by xispa** [comment]
Tested and working in 1.3
