### ISSUE TITLE
New client contacts do not have access to their own AR Templates

### ISSUE THREAD

**Issue by xispa** [senaite/senaite.core#957]
## Steps to reproduce

Client contacts have no access to those client-specific AR Templates that were created before the contact had credentials (became a member). Same issue might happen for other client-specific contents, such as Profiles, Analysis Specifications, etc.

1. Login as Labman
2. Go to client and create a new contact, but without giving him/her access to SENAITE
3. Create a new AR Template for this client only (Client edit > AR Templates)
4. Go back to the contact and give him/her credentials (Contact > Login details)
5. Logout
6. Login as the client contact
7. Go to Client's AR Templates folder

## Current behavior

Client contacts do not have access to AR Templates that belong to their own client and were created before they had access credentials.

## Expected behavior

Client contacts have access to AR Templates that belong to their own client, regardless of when they became a member with access.

**Comment by rockfruit** [comment]
Products.CMFPlone.CatalogTool.allowedRolesAndUsers() - This adds "user:x" and "user:y" to the catalog, but does not include any local role names (also explicitly removes Owner role from the index).  I'm not sure why this is, but it appears that using local roles requires that we re-index object security (at least the allowedRolesAndUsers index).  I want to avoid that re-indexing of objects, as there could be quite a few of them.

The only other solution I can think of is to delegate these local-ownership permission-checks up to the Client.

Any better ideas?

**Comment by xispa** [comment]
The better approach for this one and others related with client contact permissions is to move contacts to the site root (in their own folder) and give the privileges to labman to assign one (or more) clients to any given contact. Each time a client is created, a client-specific role/group is created too, with privileges to access to all contents from inside the client. When a contact is assigned to a client, the client-specific role is assigned to that contact (and will be removed when is unassigned). This is a nice feature/improvement that would allow us to address a lot of issues regarding contact/client permissions, but it will not be available immediately. At the moment, I am going to setup a cron or something to keep ownership of client contents up-to-date
