### ISSUE TITLE
Worksheet Rejection

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#975]
Paraphrased from comment in https://community.senaite.org/t/how-to-let-an-instrument-pass-calibration-and-validation/85

## Steps to reproduce

Create a WS, capture some results, then reject it

## Current behavior

On new 1.2.8 installation and  fresh setup data, the _Reject_ option is not available

![image](https://user-images.githubusercontent.com/1196034/43949177-0c32734e-9c8d-11e8-91a4-aa1048b0bf67.png)

On an upgraded installation it is

![image](https://user-images.githubusercontent.com/1196034/43949343-896ec844-9c8d-11e8-840a-37dd3786bc3b.png)

Using the function gives the Worksheet a _Rejected_ state, Analyses stay _To be Verified_ but I can actually manipulate them further, even verify

![image](https://user-images.githubusercontent.com/1196034/43949669-7c030e08-9c8e-11e8-90e1-e54bd5ec56f0.png)

The WS does not get listed,  one can navigate to it from the address bar

A duplicate WS for retesting does not get created

## Expected behavior

When a Worksheet is rejected, it should create a copy of the old one for retesting and hyperlink the two. This is essential for big worksheets failing QC - else many pages of An have to be retracted manually

The rejected WS gets a _Rejected_ state, its Analyses too. If _Rejected_ is not available for An (cannot remember), they should at minimum be retracted

No action buttons for An on the rejected WS must be made available, they are untouchable

_**Edit**_

A _Rejected_ filter is required for WS lists too

![image](https://user-images.githubusercontent.com/1196034/43950030-80115d82-9c8f-11e8-84f1-796f519560c1.png)

**Comment by xispa** [comment]
Strongly related #976 (basically, remove "Retract Worksheet" action)

**Comment by xispa** [comment]
Revisited in 1.3
