### ISSUE TITLE
Worksheet Retraction is redundant

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#976]
Rather than _Retracting_ a whole Worksheet, users could _Reject_ it. Like for ARs with no _Retract_ option,  Analyses are more often retracted for retesting individually

## Steps to reproduce

Create a WS, capture its results and advance it to 'To be verified', then _Retract_ it

![image](https://user-images.githubusercontent.com/1196034/43950627-1f136f46-9c91-11e8-9c27-bf06b188b93d.png)

## Current behavior

The WS changes to _Open_, and its An stay _To be verified_

![image](https://user-images.githubusercontent.com/1196034/43950752-83b7f796-9c91-11e8-9767-47aa7faac372.png)

## Expected behavior

The WS Retract option can be removed, in line with ARs

**Comment by xispa** [comment]
Fixed in 1.3
