### ISSUE TITLE
Analysis retraction does not impact To be Verified WS state

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#977]
related to https://github.com/senaite/senaite.core/issues/976

## Steps to reproduce

Create a WS, capture some results, and advance it to _To be Verified_. Retract one Analysis for retesting

## Current behavior

The Analysis is retracted OK to _Received_ state, the WS stays to _To be Verified_

![image](https://user-images.githubusercontent.com/1196034/43951116-86b4ebe2-9c92-11e8-9271-8a6d96505636.png)

## Expected behavior

The WS to reverse cascade and assume the state corrsponding  to the lowest state of the An it contains. In this case the WS state should be _Open_

**Comment by xispa** [comment]
Fixed in 1.3
