### ISSUE TITLE
Cannot edit Interim Field titles on AS

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#995]
We are making good progress doing both DM and Unit Conversion in Calculations by allowing selected Interims to be displayed on the COA, single ARs sofar, multi column COA will be tricky, https://jira.bikalabs.com/browse/LIMS-2932

Earlier I got the issue reported here, struggled to reproduce it but somehow got it now again:

## Steps to reproduce

Open an AS that uses a Calculation with Interim fields, navigate to its Method tab and edit some of the Interim field titles, e.g. here, _Primary_ to _Primary unit_, Save

## Current behavior

The System demands the Interim Title to be the same as originally used on the Calculation itself, e

![image](https://user-images.githubusercontent.com/1196034/44078739-9767d04a-9fa7-11e8-94f9-0ca605047e2b.png)

## Expected behavior

The user should be able to modify Interim field titles per AS

**Comment by rockfruit** [comment]
If the user wants to have a different title, the keyword will have to change also.  The keywords are used in the rendering to place identical interims into the same column/row - and so if the keyword has multiple titles, it will be impossible to realise this in the UI.

**Comment by lemoene** [comment]
ah, to be documented
