### ISSUE TITLE
Calculated results not submitted 

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#998]
## Steps to reproduce
Create an AR with ASs with calculation that depends on an other AR(s).
Receive AR and enter results.

## Current behavior
After entering all results and interims all values are marked for submission,
After submitting all values some calculated results reside in the state "received".
But the results are stored anyhow. They have to picked and marked again for submission, that works afterwards.

Observed on my freshly updated (->1.2.8) test machine. Only some of the calculated ASs, that depend on other ASs, are concerned, but not everytime.

## Expected behavior
All results marked for submission shall be submitted whether calculated or not.

## Screenshot (optional)
Situation:
![grafik](https://user-images.githubusercontent.com/25460329/44169511-eb89fd00-a0d4-11e8-8f2d-eef92ffa1fea.png)

First entry marks third AS, although it cannot be calculated yet (weird?):
![grafik](https://user-images.githubusercontent.com/25460329/44170680-5b4db700-a0d8-11e8-9d11-17896ea7d239.png)

Second entry calculates second result:
![grafik](https://user-images.githubusercontent.com/25460329/44170753-964fea80-a0d8-11e8-93fa-f37ca78323b4.png)

Third entry triggers calculation of last result:
![grafik](https://user-images.githubusercontent.com/25460329/44170836-d8792c00-a0d8-11e8-90ea-bf3f54724bcd.png)

Situation after submitting all three results:
![grafik](https://user-images.githubusercontent.com/25460329/44170940-2beb7a00-a0d9-11e8-8382-7d9da8afcafa.png)

**Comment by grulisco** [comment]
I copied the calculations and ASs into demo site senaite.ridingbytes.com with the same effect, see

![grafik](https://user-images.githubusercontent.com/25460329/44199643-f2505880-a144-11e8-9fb5-f70810e7f544.png)

BTW those calculations worked before correctly.

**Comment by grulisco** [comment]
I just updated our testmachine to current master.
First tests show that this problem does not occur again.

**Comment by grulisco** [comment]
Problem occurs again after update to v1.2.9, weird...

**Comment by grulisco** [comment]
see also https://senaite.ridingbytes.com/clients/client-3/H2O-0003-R01/manage_results

Maybe the problem is, that the calculation depends on other ASs **and** on its own interim field...

**Comment by xispa** [comment]
Basically, analyses (selected or not) must be submitted automatically...
a) as soon as all the analyses it depends on (if any) are submitted **and** 
b) all its own interim fields (if any) have a value set.

Rephrasing:
An analysis must be submitted automatically if its final result can be calculated because of the submission of others.

**Comment by ramonski** [comment]
Just stumbled upon the bug. The issue remains here:
https://github.com/senaite/senaite.core/blob/master/bika/lims/browser/analyses/workflow.py#L142
The results come in as an arbitrary sorted dictionary. Therefore, it might be that the calculated analysis comes in *before* its dependencies, which fails here:
https://github.com/senaite/senaite.core/blob/master/bika/lims/browser/analyses/workflow.py#L144

**Comment by grulisco** [comment]
At the moment on our testmachine (v 1.2.9) none of the calculated results get submitted in the first run.

**Comment by xispa** [comment]
is this issue still a problem?

**Comment by grulisco** [comment]
No, I didn't encounter this issue again in the last weeks testing with nearly current master.
I was not sure, whether it is up to you developers or to **me** to close this issue...

**Comment by grulisco** [comment]
OK:)
